### ISSUE TITLE
write_new_in_dat.py says there are variable definitions on multiple lines when none exist

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1007]
In GitLab by @schislet on Feb 11, 2020, 10:15

[IN2.DAT](https://git.ccfe.ac.uk/process/process/uploads/dd745e561795c4feace2394d46248af7/IN2.DAT)

running write_new_in_dat.py with the above input file results in the following error, despite there not being any variable definitions over multiple lines. 

Error when reading IN.DAT file on line [' \n']
 Please note, that our Python Library cannot cope with  variable definitions on multiple lines.

@jmorris-uk @jonmaddock

**Comment by clmould** [comment]
In the attached input file, the line immediately after `*-------------------Scan Module--------------------*` contained a space and was causing the issue described. Have edited the `remove_empty_lines` function in process/io/in_dat.py to now treat lines containing only spaces as an empty line and remove them
