### ISSUE TITLE
Plot Proc Diagram with Resistive Coils

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1031]
In GitLab by @stuartmuldrew on Mar 23, 2020, 11:52

The inboard magnet build for cryo-aluminium magnets is being plotted incorrectly in the poloidal cross section plot of plot_proc:

![Screenshot_2020-03-23_at_11.49.00](https://git.ccfe.ac.uk/process/process/uploads/1824fc30963ed9a41526eae69a68af8c/Screenshot_2020-03-23_at_11.49.00.png)

Ref: @skahn @asbrown

**Comment by clmould** [comment]
@chris-ashe We have tested with a cryo-aluminium TF coil conductor and this error cannot be reproduced so will close the issue.
