### ISSUE TITLE
Costing superconductors in all coils using dollars per kAm rather than dollars per kg

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1038]
In GitLab by @schislet on Apr 14, 2020, 09:01

Associated branch: https://git.ccfe.ac.uk/process/process/-/tree/issue-1037

## Summary

The superconducting industry uses the metric $/kAm as the costing figure of merit for superconductors rather than $/kg. A switch has been added into costs.f90 such that when supercond_cost_model = 1, the superconductor costs are calculated using this metric rather than the existing $/kg metric (which is selected by default for supercond_cost_model = 0). 

The cost of the superconductor is a function of the operating field, temperature and strain (though we shall assume that the strain on the superconductor itself is zero):

[Strand/Tape Cost ($/kAm) under operating conditions] = [Strand/Tape Cost ($/kAm) under reference conditions] * [Strand/Tape Jc under reference conditions] / [Strand/Tape Jc under operating conditions]

The strand/tape costs ($/kAm) under reference conditions were taken from Cooley 2005 [1] and Cooley 2016 [and back converted into 1990 US$ assuming standard CPI inflation. At 6 T and 4.2 K these are 4.8 $/kAm for Nb3Sn strands (calculated from table 3 of [1]), 1.0 $/kAm for Nb-Ti (calculated from table 2 of [1]) and 47.4 $/kAm for REBCO (calculated from slide 3 of [2]). 

The strand/Tape Jcs under reference conditions were calculated by manually calling the critical current scaling laws contained between superconductors.90 and sctfcoil.f90 at 6 T and 4.2 K. The Jcs were collected into the list variable j_crit_str_0. 

The strand/tape Jcs under operating conditions are acquired from the variables j_crit_str_pf, j_crit_str_cs and j_crit_str_tf which pull the strand Jcs from sctfcoil.f90 and pfcoil.f90 when they are invoked inside the pfcoil and ohcalc subroutines in pfcoil.f90 and inside the tfspcall subroutine inside sctfcoil.f90. 

From there

[Cost ($/m)] = [Cost ($/kAm) under operating conditions] * [Cable peak operating current (kA)]

The cable peak operating currents are acquired from abs(ric(i)/turns(i)) for the pf conductor, abs(ric(nohc)/turns(nohc)) for the cs conductor and cpttf for the tf conductor (converted to kA).  

[1] [Cooley_2005_Cost_of_strands_0953-2048_18_4_R01.pdf](https://git.ccfe.ac.uk/process/process/uploads/9c681128384fbbc48a955b1c114f892f/Cooley_2005_Cost_of_strands_0953-2048_18_4_R01.pdf)

[2] [Cooley_2016.pdf](https://git.ccfe.ac.uk/process/process/uploads/3dc9aead88ee47ce862042153db0a13e/Cooley_2016.pdf)

## Checklist

After implementing issue do the following

* [x] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by mkovari** [comment]
Hi Jack, I notice that you have created this variable:

> superconductor strand critical current density under operating conditions in central solenoid (A/m2). Necessary for the cost calculation in $/kA m

I would have thought that the cost in $/(kA m) was based on the critical current for standard test conditions, not the operating conditions, which obviously the manufacturer doesn't know.

Have I got the wrong end of the stick?

**Comment by j-a-foster** [comment]
That's calcuated in `pfcoil.py` based on the temperature and field calculated during a run. The variable `j_crit_str_0` in `tfcoil_variables.f90` is the reference conditions.

**Comment by mkovari** [comment]
OK, I see.
