### ISSUE TITLE
TF coil: Resistive magnet Young's modulus

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1046]
In GitLab by @skahn on May 12, 2020, 16:27

## Description

The presence of inter-turn insulation is not present in the resistive stress calculation. The Young's modulus must be modified to take this into account. As the fraction taken by the insulation varies as a function of the radius, the corresponding Young's modulus will be radially dependent

## Proposed actions

* [x] Change the vertical young modulus to take the cooling and the insulations into account.
* [ ] Modify the toroidal smeared young modulus expression to take insulation layer as a function of R and see if an analytical solution still holds.
* [ ] Find a way to take the cooling channels effect on the toroidal/radial Young modulus.

Best regards     
Seb
Ref : @stuartmuldrew, @mkovari and @jmorris-uk

**Comment by mkovari** [comment]
> Modify the toroidal smeared young modulus expression to take insulation layer as a function of R and see if an analytical solution still holds.

> We would need to develop a model for the positions of the cooling channels, to get a radially dependent calculation of Young's modulus

Deriving a radially dependent Young's modulus may be easy, but obtaining an analytical solution looks very difficult to me unless you already understand Seb's mathematics, and maybe even then.
