### ISSUE TITLE
Beta limit for Spherical Tokamaks (ST)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1047]
In GitLab by @mkovari on May 19, 2020, 11:02

Jack Berkery et al of Columbia looked at 5000 experimental equilibria and produced a fit of the calculated no-wall beta limit against aspect ratio, internal inductance and pressure peaking. It is for NSTX so it should be relevant to ST reactors.   

![image](https://git.ccfe.ac.uk/process/process/uploads/a45d54a0c27a91df65eef2929d6d9451/image.png)    
where  
![image](https://git.ccfe.ac.uk/process/process/uploads/4b4c922da296b857fdeec6c863a203e9/image.png)  
(The "poloidal magnetic field" has not been defined - see comments.)   
https://iopscience.iop.org/article/10.1088/0029-5515/55/12/123007/pdf  

The dependences in this fit are plotted here:[Beta_limit.pdf](https://git.ccfe.ac.uk/process/process/uploads/2b810bc11d1a80b0a86756e776d22579/Beta_limit.pdf)

The key limits of applicability are
$`A<1.8`$, 
$`l_i>0.4`$

Including the wall will make things more difficult as it depends on the geometry of the wall - especially how far it is from the plasma edge.  This draft paper looks at this for MAST-U.

[MAST-U_globalstability_v21.docx](https://git.ccfe.ac.uk/process/process/uploads/12707803e4dbafc21a2bd8a51d159c4b/MAST-U_globalstability_v21.docx)

The most conservative assumption is the no-wall limit. When a conducting wall is present the growth rate of unstable modes just above this limit is greatly reduced.  Plasma rotation and kinetic effects can then make these modes stable, or they can be actively controlled. The use of ferromagnetic material such as Eurofer in the wall also has an effect. As all this is difficult to quantify, Chris Ham suggests we could go for the no-wall limit plus some percentage, e.g. no-wall limit times 1.2. We could make this a user input, `resistive_wall_factor`.  
$`\beta_{N,max}=f_{resistive-wall} \times \beta_{N,no-wall}`$

This approach still requires sensible values for $`l_i`$ and $`p_0/\langle p \rangle `$, which is a matter for another day.

Any comments @stuartmuldrew, @schislet ?

## Checklist

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by mkovari** [comment]
Please note that normalised internal inductance is discussed at length in #1878.

**Comment by stuartmuldrew** [comment]
Section 2.4 of Emmi's paper explains how the Beta limit is set in JETTO scans: https://arxiv.org/pdf/2403.09460

This requires the pressure peaking, $F_p =p_{ax}/ \< p \>$, to set the Beta limit with $C_{\beta} = \frac{(\beta_N-3.7)F_p}{12.5-3.5F_p}$, where $C_p \le 0.5$ (see paper for explanation).

I don't think we have the pressure peaking in PROCESS, so it might be worth implementing the above instead.

**Comment by mkovari** [comment]
The formula from Emmi's paper looks good, although there is no actual justification or reference for it in the paper.  PROCESS has profiles for density and temperature, so the pressure peaking factor $F_p$ can be calculated.  

However, we normally keep the density and temperature profile exponents constant, so we don't fully make use of the parameter space.  It would make sense to start using these as iteration variables.

**Comment by stuartmuldrew** [comment]
I've added Emmi's equation as `iprofile` option 6.
