### ISSUE TITLE
Connection length used in long legged divertor SoL physics models

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1051]
In GitLab by @ajpearcey on Jun 1, 2020, 13:49

## Summary

The connection length used in the Kallenbach model is calculated as
```
lcon = lcon_factor * (pi*q*rmajor/93.2) * (21.25*log(1/lambda_q_omp)-8.7)
```
This comes from a fitting to field lines in and is discussed in issue #494 and updated and improved in #497 .

We need to investigate and validate this fit for the case of log legged divertor design and if it's no longer valid suggest a replacement for this new regime.

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by geograham** [comment]
Kallenbach model is not currently used, see #1886.
