### ISSUE TITLE
NASA triangular cost and schedule distribution

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1059]
In GitLab by @asbrown on Jun 16, 2020, 12:16

## Summary

As part of the development of the new costing model, costs_step.f90 (cost_model = 2), a new probabilistic cost estimation will be introduced as spelled out in the attached paper ["An Independent Cost and Schedule Estimate Process for NASA Science Projects"](https://git.ccfe.ac.uk/process/process/uploads/2373a061d144dfcf9247a3d385eac07d/Kellogg_2016_NASAcosting.pdf).

The paper describes a 'typical triangular cost & schedule distribution' (see below):
![image](https://git.ccfe.ac.uk/process/process/uploads/30ef77117b4c4a9dbea05413ffaedef7/image.png)

A triangular errortype will be put in process_config.py for use through the evaluate_uncertainties.py utility.

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by j-a-foster** [comment]
This can be done quite easily but currently `test_uncertainties_evaluate.py` is skipped on the CI as it takes "too long". Either the change can go in untested, or this will have to wait until the test is added back in to the CI.

**Comment by j-a-foster** [comment]
Closing issue as the uncertainty tools in PROCESS are to be replaced soon.
