### ISSUE TITLE
Remove scipy.zeros from Python Utilities

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1110]
In GitLab by @stuartmuldrew on Sep 11, 2020, 12:17

Following python warning:

%../process/utilities/mfile_comparison.py:117: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
  values = scipy.zeros(n)

**Comment by cjwgriesel** [comment]
This has been done but bizarrely it fails the integration test for just changing scipy to numpy !!!!

**Comment by timothy-nunn** [comment]
Fixed by #3149, issue was not linked to PR properly so was never closed
