### ISSUE TITLE
Cryoplant power constraint

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1121]
In GitLab by @skahn on Oct 1, 2020, 12:07

## Description 

Some cryoplant power consumptions (150 MW) would mean using the superficy of oxford for it. To avoid such effect on the desing, it might be interresting to set constraint limit for the cryogenic power consumption.

## Tout doux list

* [x] Add `crypmw_max` as user input
* [x] Add `f_crypmw` as iteration variable
* [x] Add the constraint equation
* [x] Use the constraint on some inputs files

The constraints works as expected and is being used. Ready to be merged : https://git.ccfe.ac.uk/process/process/-/merge_requests/356

Corresponding branch: https://git.ccfe.ac.uk/process/process/-/tree/issue-1120-cryopower-constraint
Corresponding merge request: https://git.ccfe.ac.uk/process/process/-/merge_requests/356

Best regards    
seb

ref : @stuartmuldrew

**Comment by mkovari** [comment]
I don't think any action is needed here.  The upper limit on the cryogenic plant power for the TF coil (constraint 87) is available but you don't have to use it.

**Comment by jmorris-uk** [comment]
See above, issue closed.
