### ISSUE TITLE
Vertical build consistency

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1128]
In GitLab by @skahn on Oct 8, 2020, 11:46

## Description 

Not sure the vertical build is entirely consistent. 
I would expect for double null the TF vertical bore to be `2.0D0 * hmax`, but it does not seems to be the the way it is treated.

code extraction
```
    ! Height to inside edge of TF coil
    ! Rem SK : definition only valid for double null! 
    hmax = rminor*kappa + vgap + divfix + shldlth + ddwi + vgap2 + thshield + tftsgap

    ! TF coil vertical bore [m] (Not sure it is entirely consistent !)
    ! Rem SK : not consistend for single null!
    dh_tf_inner_bore = 2.0D0*(rminor*kappa + vgaptop + fwith + blnktth + vvblgap + &
        shldtth + ddwi+ vgap2 + thshield + tftsgap)
```

## Proposal 

Set `dh_tf_inner_bore = 2.0D0 * hmax` if the double null option is considered.

Ref : @jmorris-uk, @mkovari and @stuartmuldrew 

Best regards     
Seb

**Comment by ym1906** [comment]
@mkovari I see the changes you have made have clarified this code, so I will close the issue.

I think a more systematic scheme for the build variables sounds like a great idea.
