### ISSUE TITLE
plot_proc.py fails if heating is not ecrh or nbi

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1139]
In GitLab by @asbrown on Oct 13, 2020, 15:00

In `plot_proc.py` the current drive function has options for ecrh and nbi, but if `iefrf=4` (Ehst Lower Hybrid) is selected then `plot_proc.py` will fail as the array `data` is not created but later in the code data.append is used.

```
    if ecrh:
        data = [(pinjie, "Steady state auxiliary power", "MW"),
            ("pheat", "Power for heating only", "MW"),
            ("bootipf", "Bootstrap fraction", ""),
            ("faccd", "Auxiliary fraction", ""),
            ("facoh", "Inductive fraction", ""),
            ("powerht", "Plasma heating used for H factor", "MW"),
            (pdivr, r"$\frac{P_{\mathrm{div}}}{R_{0}}$", "MW m$^{-1}$"),
            (pdivnr, r"$\frac{P_{\mathrm{div}}}{<n> R_{0}}$",
             r"$\times 10^{-20}$ MW m$^{2}$"),
            (flh, r"$\frac{P_{\mathrm{div}}}{P_{\mathrm{LH}}}$", ""),
            (hstar, "H* (non-rad. corr.)", "")]
```

Another data array for Ehst Lower Hybrid to be made in the current drive function and an else statement to catch future current drive options.

**Comment by ym1906** [comment]
This issue was resolved and merged, see pull request.
