### ISSUE TITLE
Custom Build Targets and CI

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1177]
In GitLab by @mkovari on Nov 18, 2020, 14:44

The following are probably not needed any more. They take a lot of compilation time so they should be removed asap if appropriate. @jonmaddock @stuartmuldrew @ajpearcey @skahn ?  
`developerguide`  
`utilitiesdoc`  
`optsolverdoc`  
`tfdoc`.

**Comment by timothy-nunn** [comment]
Issue references PDF building CI jobs that are no longer in the code
