### ISSUE TITLE
write_new_in_dat python tools doesnt update array iteration variables

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1195]
In GitLab by @ajpearcey on Dec 8, 2020, 10:32

When using the write_new_in_dat python tool to make an IN.DAT from a PROCESS MFILE.DAT, the new IN.DAT doesn't update the iteration varibles starting point if they are part of an array. For instance fimp(13).

**Comment by timothy-nunn** [comment]
Closed by #3324
