### ISSUE TITLE
An O1-ECRH heating constraint for stellarators

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1196]
In GitLab by @jlion on Dec 8, 2020, 11:56

# An ECRH Constraint for stellarators

For stellarators the ECRH puts relevant constraints on the operation space which need to be included. It is:

```math
\omega_{pe}^2 < \omega_{gyro}^2 < \omega_{max}^2
```
where $`\omega_{pe}`$ is the plasma frequency, $`\omega_{gyro}`$ the gyrofrequency and $`\omega_{max}`$ the maximum available gyrotron frequency (now user set).

For O1 heating this implies two constraints:
```math
n_e<n_{e,crit}^{ECRH} = \frac{m_e \epsilon_0}{e^2} \omega_{gyro}^2~~\text{and}~~\omega_{gyro}<\omega_{max}.
```

**PROCESS now checks with `constraint equation 85` if an operation point at $`n_{e,crit}^{ECRH}`$ and $`B_{max}^{ECRH}`$ is ignited.**

 - `max_gyrotron_frequency` is now an input parameter and sets the maximal available gyrotron frequency.
 - `te0_available` is a new iteration variable that the ECRH needs to achieve at the ignition point (iteration variable 175)

**Comment by ym1906** [comment]
This was merged into PROCESS when the stellarator models were originally put in. This issue appears to be simply describing some of the work done. There is already a comment to describes this in the documentation.
