### ISSUE TITLE
Figures missing - Engineering Models > Machine Build

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1197]
In GitLab by @ktuakli on Dec 9, 2020, 08:49

## Summary
Just a heads up.

The first two figures on the 'machine build' page under 'engineering models' are broken/missing.

http://process.gitpages.ccfe.ac.uk/process/eng-models/machine-build/

**Comment by chris-ashe** [comment]
The figures are present in the current docs and this is no longer an issue
