### ISSUE TITLE
Calculation of bremsstrahlung

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1231]
In GitLab by @mkovari on Jan 14, 2021, 14:43

Issue #1230 showed that `function pbremden` (Bremsstrahlung radiation density) takes 32% of the total execution time (includes calls from that function).   
![image](https://git.ccfe.ac.uk/process/process/uploads/9d45020c7fa5cd572785823e5537b807/image.png)  
*As far as I can see*, the only purpose of this function is to be able to divide the total radiation into line radiation and bremsstrahlung so as to be able to output these quantities.  I think that only the total radiation is actually used in the remainder of the PROCESS calculation.  The only line I can find where the bremsstrahlung is used is
```
pline = pimp - pbrem
```
where
```
!! pimp  : output real : total impurity radiation density (W/m3)
!! pbrem : output real : Bremsstrahlung radiation density (W/m3)
!! pline : output real : other radiation density (W/m3)
```

If this is correct, then we have some simple options for speeding up the code:  
EITHER Remove this routine entirely and remove the separate output of line radiation and bremsstrahlung,   
OR calculate the bremsstrahlung only on the function call that occurs after the last VMCON iteration when the OUT.DAT will be written.

Detailed options:
1.  Replace the function `zav_of_te` by something much quicker.
2.  Reduce the number of steps in the profile integration: `npts = 200` in `subroutine imprad`.

**Comment by mkovari** [comment]
I propose to remove the separate output of line radiation and bremsstrahlung entirely.  Only the sum of the two and the synchrotron radiation will be reported.  This is to save execution time.  (If you read the comments above you may think this is not an issue, but I recall that further investigation showed that profiling carried out was incorrect in some cases.)

The line radiation and bremsstrahlung radiation seem to be used to calculate `hstar`, the non-radiation corrected value of the energy confinement factor H.  This only appears in the two-page summary, not in the OUT.DAT or the MFILE.   Please let me know if you have any objection to my removing `hstar`.

@ajpearcey @jmorris-uk @ym1906

**Comment by mkovari** [comment]
@timothy-nunn Graeme has reminded me that this code was refactored when converting to Python.  Are you able to run tools to assess whether the bremsstrahlung and impurity radiation calculations are occupying any significant execution time?

**Comment by timothy-nunn** [comment]
@mkovari I will run this test again on Thursday. From memory this was no longer a large portion of our *relative* runtime. We can also maybe discuss the removal of it all together then :)?

**Comment by ym1906** [comment]
I have no particular use for Bremsstrahlung as an output. If it is indeed inaccurate perhaps it is best to remove it.

**Comment by ajpearcey** [comment]
in PR !3110 which solves issue #438 I added the hstar calculation into the OUT.DAT

**Comment by ajpearcey** [comment]
Looking again at the hstar calculations that are now implemented in `physics.py` they only require the total core radiation and synchrotron radiation. So removing the Bremsstrahlung calculation will not effect it. Therefore if we think it best to remove the calculation it can easily be done.
