### ISSUE TITLE
Failed PROCESS run output default

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1233]
In GitLab by @skahn on Jan 14, 2021, 17:50

## Description

@mkovari had the very good idea to keep the best run in case of failed run. The issue is that only the convergence is taken into account to juge the best runs.

The result is that the best run has generally very important constraint equations errors. 

## Proposal

Use the max between the constraints residuals and convergence criteria to select the shown run

Ref : @mkovari 

Best regards    
Seb

**Comment by mkovari** [comment]
VMCON convergence parameter takes account of the convergence of the figure of merit and the constraint residuals (unless the Lagrange multiplier is zero).
