### ISSUE TITLE
Superconducting busbars

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1253]
In GitLab by @mkovari on Feb 2, 2021, 17:35

I believe that PROCESS assumes that the busbars for TF and PF coils are resistive.  It has been suggested that HTS could be used to carry the current all the way to the power supply, which would save the power dissipated in a resistive busbar.

For example,
```
 TF coil resistive power (MW)                                             (rpower)                  6.254E+00  OP 
 TF coil inductive power (MVA)                                            (xpower)                  1.817E+01  OP 
 Aluminium bus current density (kA/cm2)                                   (djmka)                   1.250E-01     
 Aluminium bus cross-sectional area (cm2)                                 (albusa)                  4.529E+02  OP 
 Total length of TF coil bussing (m)                                      (tfbusl)                  3.373E+03  OP 
 Aluminium bus weight (tonnes)                                            (albuswt)                 4.125E+02  OP 
 Total TF coil bus resistance (ohm)                                       (rtfbus)                  1.951E-03  OP 
 TF coil bus voltage drop (V)                                             (vtfbus)                  1.105E+02  OP 
```

Any volunteers @ajpearcey @jmorris-uk @asbrown ?

**Comment by mkovari** [comment]
We already have an input `rhotfbus`: 'TF coil bus (feeders) resistivity (ohm-m)'.  Anyone can just set this to zero if they want.
However, the resistivity of the PF coil bus bars are hard-coded:
https://github.com/ukaea/PROCESS/blob/65400a51231539cde422409c3c81e513a42e9492/process/power.py#L105-L108
This needs to be changed.
