### ISSUE TITLE
Fcu has two definitions

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1292]
In GitLab by @schislet on Mar 25, 2021, 12:03

## Summary

For LTS materials fcu = copper fraction of the cable conductor. For HTS materials fcu = copper fraction of the cable conductor **NOT** including the copper within the REBCO tapes themselves.

We should introduce a second variable for HTS, fcu_HTS, to make this distinction more clear. 

@mkovari @skahn 
## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by kj5248** [comment]
fcu is used as an input (fcutfsu, fcupfsu and fcuohsu) so the copper fraction would not include REBCO for HTS materials as REBCO variables are handled separately. Have made slight change to wording for the copper fraction within the documentation to make this clearer.
