### ISSUE TITLE
Add additional build costs to cost model 2

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1303]
In GitLab by @hlux on Apr 21, 2021, 15:43

## Summary

We have identified some buildings/faciclities as missing in the current cost model =2 these will need to be added after an appropriate cost model has been derived.

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by ym1906** [comment]
There is no detail about the problem or what is to be done. I am closing this issue.
