### ISSUE TITLE
Fix capital/fuel cost switch for centreposts in STEP TF cost model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1312]
Fix `ifueltyp` switch for different `i_tf_sup` cases in step_a22010301, specifically the cryo-Al case. It currently only works in the copper (`i_tf_sup == 0`) case. The Al conductor mass for the centrepost can be extracted from the `sctfcoil_module` for the purpose of working out the centrepost cost in the cryo-Al case. Recommended by @stuartmuldrew in !389.

**Comment by ym1906** [comment]
This seems like a STEP cost model issue, is that right @j-a-foster ?

**Comment by j-a-foster** [comment]
Yeah and it appears that it was implemented so this can be closed.
