### ISSUE TITLE
TF Coil Stresses (CCFE two-layer model)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#137]
In GitLab by @mkovari on Sep 24, 2014, 13:24

Please tidy up the output for the TF coil stresses.  For each stress it would be good to specify:  
a) radial, tangential, vertical or von Mises stress   
b) Case or winding pack*  
c) Inner or outer radius of case, inner or outer radius of winding pack.  

* With note stating that only the structural components of the winding pack (cable conduit plus radial plates if present) are considered.

For deflections, it would be useful to state

a) radial, tangential or vertical deflection  (radial, obviously, but it should be stated)  
b) Case or winding pack  
c) Inner or outer radius of case, inner or outer radius of winding pack.  

Do you know where the maximum deflection is?

At the head of the section should be an explanation that only the stresses in the inboard midplane are calculated.

Edit:  

I realise that to a first approximation the stresses in the outboard midplane are identical to the vertical stresses in the inboard midplane.  This is then also the outboard von Mises stress.  

The combination of compressive and tensile stress inboard will always have a higher von Mises stress than that resulting from the tensile stress alone outboard.  Therefore the outboard tensile stress due to the hoop force is never limiting.

We could write a suitable description of the vertical stress in the OUT.DAT;  
`Vertical tensile stress in the case (inboard and outboard midplanes)`    
`Vertical tensile stress in the conduit and radial plates (inboard and outboard midplanes)`  
Thanks

**Comment by ajpearcey** [comment]
I think this has already been dealt with by including the table which lists all required info.
