### ISSUE TITLE
The Lengyel model for the divertor

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1381]
In GitLab by @mkovari on Aug 17, 2021, 13:34

The exhaust group (Stuart Henderson, David Moulton et al) have implemented the Lengyel model for the divertor, with enhancements.  This is somewhat similar to the Kallenbach model (already implemented in PROCESS) but written by actual edge physicists and benchmarked against SOLPS.

This model is available in Python from Stuart Henderson.

I suggest we assess this as an alternative to the Kallenbach model.

**Comment by jmorris-uk** [comment]
Issue is too broad and the model in question would need to be fully reviewed for applicability and if it adds value to the code. The relevant information regarding the model has been migrated to discussion https://github.com/ukaea/PROCESS/discussions/3046
