### ISSUE TITLE
Determine MFILE reader strategy for collaborators

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1385]
It has come to light that various collaborators are using their own MFILE readers for a variety of reasons. These obviously aren't tested by PROCESS, if at all, and are liable to break/cause frustration/be inaccurate. We should provide one tested solution for these collaborators, and address the reasons why they created their own tools in the first place.

**Comment by stuartmuldrew** [comment]
This is no longer an issue.
