### ISSUE TITLE
Output the radiation profile

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1410]
In GitLab by @mkovari on Oct 5, 2021, 14:03

It would be very nice to have the radial profile of radiation emission.  PROCESS already calculates the radiation emission at each radius and then integrates, but at present only outputs the integral.  The profile affects the distribution of radiation on the wall.  For example, the plot on the right shows wall loads calculated using Cherab for radiation situated in different parts of the plasma.  The distribution due to core radiation (blue) and that due to pedestal radiation (orange) are signficantly different.
![image](https://git.ccfe.ac.uk/process/process/uploads/2f4782de8fb325e1dd67b2ff920c42e7/image.png)
To be useful we would probably have to output the emission per unit flux, as a function of flux.  This may not be trivial, but it will be very useful in the medium term to be able to output quantities in terms of flux.

Comments @ajpearcey @cz1743 @jmorris-uk @cjwgriesel @pc6783 ?

**Comment by ajpearcey** [comment]
Given this is plotted in the `plot_proc.py` output, i'm unsure adding this as a table into the .DAT output would be that useful. Perhaps in the future once the data structures in PROCESS are improved and with the updated profile objects there my be more utility and it maybe worth returning to this. 

Thoughts @mkovari ?
