### ISSUE TITLE
The pressure drop for the cryo plant in process is only really calculated for the centre post.

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1450]
In GitLab by @cjwgriesel on Nov 2, 2021, 14:55

In process the power that is used for pumping is only really calculated for the centre post using a darcy type formulation for friction losses etc. For SPR-025-6 the variable lcool (length of cooling channel) is calculated as lcool = 2.0D0 * (hmax + tfthko) ! Length. lcool = 15.32 m and the vertical height of SPR-025-6 is approx 14.6 m. So the length of the cooling channel does not encompass the full length of the cooling channel of a TF coil in SPR-025-6. The centre line circumferential length of a cooling channel in a TF coil in SPR-025-6 = 44.94136 m. There are 16 TF coils and it is most likely that the coils would be connected in parallel. (If they were in series then the cooling path would be 719.06m !! in length). Losses due to bends etc would also need to be included. The centre post would also need to included however is it connected in series or parallel? At the moment efficiencies are estimated for the cryoplant via a percentage found from past plant performances (where it is avialable). So the iterated result of the total length of a TF coil is what should be used to calculate the pressure drop. Bends or curves etc could be used depending on the shape of the TF coil?. The question then is how accurate should we make the estimate in Process?

**Comment by ajpearcey** [comment]
These calculation are done in the centre post model for resistive magnets. At this point it is only worth revisiting this model if also review the nuclear heating model for superconducting magnets in PROCESS. Until we have need for these models again, i suggest we drop this task.
