### ISSUE TITLE
FNSF failure when run solo

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1490]
In GitLab by @timothy-nunn on Nov 25, 2021, 11:25

The FNSF regression test fails when run on its own:

![image](https://git.ccfe.ac.uk/process/process/uploads/dcd10fefb08b8734178307fc7989f9cd/image.png)

This appears to be caused by memory issues:[valgrind_fnsf.log](https://git.ccfe.ac.uk/process/process/uploads/01e4decbaea98f8ec8dc649fb501655e/valgrind_fnsf.log)

**Comment by timothy-nunn** [comment]
FNSF regression test no longer in suite
