### ISSUE TITLE
PF coils

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#152]
In GitLab by @mkovari on Nov 11, 2014, 12:27

Tidy up inconsistencies.  
Change default to NbTi.  
Remove "steel thickness" column.  
Remove 2/3 factor from stress calc.  
Max permissible tensile stress same default as for TF and CS.  
No need for temp margin.  
Current density safety factor (input).  
Calculate actual J.  
Derive sizes incl. steel.

**Comment by jonmaddock** [comment]
How much of this is already done, or no longer relevant? Perhaps it can be finished, or split up into the remaining tasks?

**Comment by ajpearcey** [comment]
Tidy up inconsistencies.
Change default to NbTi. - dont change
Remove "steel thickness" column. - remove as there should only be a conduit 
Remove 2/3 factor from stress calc. - has been replaced by `sigpfcf` which is set to 2/3. will be removed.
Max permissible tensile stress same default as for TF and CS.  - now TF and CS stress are separate - will be same as CS
No need for temp margin. YES!
Current density safety factor (input). - rjconpf - check for safety factor and how it's calculated
Calculate actual J. 
Derive sizes incl. steel. - add conduit

**Comment by ajpearcey** [comment]
Going through an making sense of what is in the PF coils models 

I will leave the default PF coil conductor material as `isumatpf=1` which is the ITER Nb3Sn critical surface model. 

The model assumes that all the steel in the PF coil is in a case that encloses the PF coil winding pack and its thickness is determined by a calculation of the thickness required to keep the stress below `sigpfcalw` (defaultly 500MPa). The model used to assume the 2/3 of the force was supported by the steel. The steel thickness is used is other areas of the code to calculate things like weights and costs. Something similar is done in the CS coil, but with the comment 
```
Thickness of hypothetical steel cylinders assumed to encase the PF along
its inside and outside edges; in reality, the steel is distributed
throughout the conductor.
```
The factor 2/3 will be replaced with a factor 1. The steel requirement calculation based on the stress limits will be left but a comment will be added to reflect that this steel is spread across the PF coil. This steel thickness will be removed from the output, while PF coil steel mass will be left.   

 There is no safety factor for the current density in the winding pack. This could be added, thoughts? @mkovari

**Comment by mkovari** [comment]
We definitely need a margin below the critical current density.  Since the PF coils are exposed to large field variations resulting in AC losses (as is the CS), this be be fairly substantial - maybe a factor of 2?  We could have a look at the documentation.
