### ISSUE TITLE
starfire regression scenario has never had a valid TF coil build

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1524]
In GitLab by @pc6783 on Jan 12, 2022, 17:27

The starfire regression scenario has never had a valid TF coil build. As far as I can tell, the conduit thickness has always been larger than the total turn thickness, resulting in negative conductor area.

For stress purposes, this also results in a negative Young's modulus.

**Comment by timothy-nunn** [comment]
starfire regression test not in test suite anymore
