### ISSUE TITLE
Calling of avail from Stellarator/IFE does not take into account iavail

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1541]
In GitLab by @timothy-nunn on Jan 25, 2022, 11:21

As per discussion in !601, IFE/Stellarator call the availability model. However, they both call the `avail` subroutine without taking into account the `iavail` flag. However, other calls to availability models take into account the `iavail` flag:

```python
if cv.iavail > 1:
    self.avail_2(output)  # Morris model (2015)
else:
    self.avail(output)  # Taylor and Ward model (1999)
``` 

Is this intended behaviour or should they be calling availabilities `run` method and allowing it to run the appropriate model based upon the switch?

**Comment by chris-ashe** [comment]
For the `ife` module their is dedicated inertial fusion conditions in the `avail` routine that is ran. Though these just turn off parts of the routine that represent components not seen in inertial fusion eg (DEMO styled blankets).

For the stellarator module the `avail` routine is run as well. Though I don't see why it couldn't run the `avail_2` routine.
Most availabilities are just calculated as a time require to reach a certain fluence when operating at a certain fusion power so should be goof enough as a proxy for estimating lifetimes.

**Comment by chris-ashe** [comment]
Issue closed as per:
https://github.com/ukaea/PROCESS/pull/3037
