### ISSUE TITLE
FORD docs missing variable intial values

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1549]
In GitLab by @ajpearcey on Jan 31, 2022, 13:12

The FORD docs (http://process.gitpages.ccfe.ac.uk/process/vardes/) list variable initial values as "none".

I believe this is due to the intialisation now being done it is own subroutine in the fortran. For example `subroutine init_physics_variables`

**Comment by jonmaddock** [comment]
@timothy-nunn is this still the case, or has this already been fixed?

**Comment by timothy-nunn** [comment]
Solved by #2808
