### ISSUE TITLE
Add option to use PLASMOD plasma resistance calculation

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1616]
In GitLab by @ajpearcey on Mar 23, 2022, 17:04

add switch to allow for use of PLASMOD  plasma resistance calculation instead of Uckan scaling relation.

**Comment by ajpearcey** [comment]
We have now removed PLASMOD from PROCESS therefore I do not think this is so relevant anymore. I do think looking into more detailed plasma physics models is a good idea, but that is beyond the scope of this issue.
