### ISSUE TITLE
HCD cost output is not transparent

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1640]
In GitLab by @cz1743 on Apr 27, 2022, 10:12

The output of cost account step220104, 22.01.04 Auxiliary Heating and Current Drive (step_a220104), would be more useful with the addition of a line detailing how much of that cost is due to the energy used at start-up (set using cv.startupratio).

**Comment by j-a-foster** [comment]
Closing as this is captured in the the STEP cost model repo.
