### ISSUE TITLE
Cant find feasible solution with net electric constraint on. (icc =16)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1654]
In GitLab by @mn3981 on May 13, 2022, 14:10

There is situations where the net electric constraint `icc=16` will cause PROCESS to not be able to find a solution for a given net electric output even though it can find a solution with the same net electric output with `icc=16` turned off.
There is also situations where solutions can be found with the constraint on but past the f-value designated by the input (`ixc = 25`).

**Comment by mkovari** [comment]
I suspect the particular convergence problem identified here was due to failing to use the right iteration variable and also the error (now fixed) in constraint 81, so I will close.
