### ISSUE TITLE
Better conducted power to TF coil cold mass

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1656]
In GitLab by @pc6783 on May 16, 2022, 15:16

Currently, the heat conducted to the TF coils is assumed to be 2 W/m^2. This can be seen in this line in `plant_power.f90`:

`if ( i_tf_sup == 1 ) qss = qss + 2.0D0*tfsai`

where `qss` is the steady-state heat load to the cold mass in Watts, and `tfsai` is the area of the inboard TF coil legs in m^2. 

This level of fidelity is a fine first approximation. The next level of fidelity could increase the accuracy by a lot. Here at PPPL our engineers commonly use a combined conduction and many-layer radiation model to estimate this power. We assume a specific ordering of materials (thermal shield, polished gold radiation gap, MLI + spacer, coil), but I'm open to input on how to provide sufficient generality. 

I'd be interested to hear from @mkovari and @stuartmuldrew on how best to implement this.

Thanks

**Comment by mkovari** [comment]
I have incorporated this into Discussion #2925, and closed this issue.
