### ISSUE TITLE
Wrong variable output aswp is output as awptf

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1703]
In GitLab by @cjwgriesel on Jun 29, 2022, 09:18

In sctfcoil.f90
at line 5044
call ovarre(outfile,'WP cross section area (per coil) (m2)','(aswp)', awptf)

it can be seen that the wrong variable is output extremely simple to fix

**Comment by cjwgriesel** [comment]
This has been fixed in issue 724 and therefore this issue can now be closed
