### ISSUE TITLE
CS Cost Model update

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1708]
In GitLab by @cz1743 on Jul 6, 2022, 09:01

See https://git.ccfe.ac.uk/process-step/process-step/-/issues/106 for details.

**Comment by jonmaddock** [comment]
Perhaps this can now be closed, as it's been merged?

**Comment by j-a-foster** [comment]
Closing as issue in old GitLab repo was moved to cost model repo.
