### ISSUE TITLE
The variable t_cable becomes -ve in the process of fitting the cable pack within the tf coil

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1767]
In GitLab by @cjwgriesel on Oct 13, 2022, 11:33

In the calculation of fitting a cable pack within the TF coil an error occurs that causes t_cable to become -ve. This is clearly wrong, and a final feasible solution is created when in fact it is not a feasible solution. This needs to be investigated. I believe that a temporary fix is available? The problem is for a fixed cable size will a cable pack made for this fit within the available space within a TF coil. The fixed cable size can either be round or square. Possibly an error in the size calculation of the cables?

**Comment by mkovari** [comment]
See discussion #2923.
