### ISSUE TITLE
Updated Blanket Cost Model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1768]
In GitLab by @lg5236 on Oct 17, 2022, 16:06

## Summary

The blanket cost model needs updating with a material-based approach.  
The total blanket volume is used and multiplied by several volume percentages to give masses/costs for each section
This is best summarised in the spreadsheet ('Material-Based Costs' tab):
https://ukaeauk.sharepoint.com/:x:/s/STEP_Cost_Modelling_A5/EatrpgkQ-sBKqufh8TAOp0YBV1LzbE44yIJs3W5DQ_ZIEA?e=NfdkSZ

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by j-a-foster** [comment]
Closing as this is captured in the the STEP cost model repo.
