### ISSUE TITLE
Updated Divertor Cost Model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1769]
In GitLab by @lg5236 on Oct 17, 2022, 16:09

## Summary

The divertor cost model needs updating with a material-based approach.
Divertor surface areas are used to calculate volumes and costs from material unit rates.  More discussion is likely required.
This is best summarised in the spreadsheet ('Material-Based Costs' tab):
https://ukaeauk.sharepoint.com/:x:/s/STEP_Cost_Modelling_A5/Edas8A1QvjhCrja0oucGSx4BOVrCYrccgDY7J2z74eq9tg?e=LKEtkL

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by j-a-foster** [comment]
Closing as this is captured in the the STEP cost model repo.
