### ISSUE TITLE
Create subset of regression tests for fast local running

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1777]
The 24 regression tests take a long time to run. A subset should be defined (with good coverage) that can be run quickly locally before pushing, when the CI will run the full set.

@stuartmuldrew and @ajpearcey can you define a subset of the regression tests (perhaps 5 or so) that provide reasonable test coverage?

**Comment by timothy-nunn** [comment]
Not applicable anymore--should be considered if/when we expand the regression test suite.
