### ISSUE TITLE
Testing of TF coil options

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1786]
In GitLab by @mkovari on Dec 9, 2022, 15:23

The gitpages [lists ](http://process.gitpages.ccfe.ac.uk/process/eng-models/tf-coil/#turns-geometry) 4 options for defining the number of turns and the dimensions of the turns of the TF winding pack.

Do regression tests exist for all 4 options?
(See #723)
@jmorris-uk @timothy-nunn @jonmaddock

**Comment by chris-ashe** [comment]
The tests for the 4 turn specifying options are found in `test_sctfoil.py`

- For integer turn parametrisation with `n_layer` and `n_pancake` the test is found in `TfIntegerTurnGeomParam`
- For current per turn parametrisation, `cpttf`. It is covered in the `SuperconParam` , `ResTfInternalGeomParam` and `TfAveragedTurnGeomParam`

There is no specific tests for `t_turn_tf` and `t_cable_tf`, though there are present with an input switch in `TfAveragedTurnGeomParam`

**Comment by mkovari** [comment]
My suggestion is that ideally all these options would be covered by a regression test.  To save time it doesn't have to run with a very tight convergence tolerance - `epsvmc = 1e-4` would be adequate.

Obviously we can't have a regression test for every combination of options, but there is a lot of scope for things to go wrong in the TF coil
