### ISSUE TITLE
Follow-up from "Resolve "Python 3.10 support in build system""

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1796]
In GitLab by @timothy-nunn on Jan 11, 2023, 14:00

The following discussion from !854 should be addressed:

- [ ] @timothy-nunn started a [discussion](https://git.ccfe.ac.uk/process/process/-/merge_requests/854#note_235430): 

    > The build for Python 3.10 is not working on Mac but that will be on me to fix as the only Mac user.

**Comment by timothy-nunn** [comment]
The build has since been fixed, I am unsure which issue/commit did this.
