### ISSUE TITLE
Pythonise bootstrap_fraction_sauter() function in physics.f90 and integrate refactored PlasmaProfiles with it

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1821]
In GitLab by @ym1906  on Mar 31, 2023, 09:58

The function bootstrap_fraction_sauter() calculates its own version of t and ne profiles and integrates them. For consistency and efficiency it should use the refactored Plasma Profiles which already hold this data.

Tasks:
* Convert the function to python.
* Determine whether a unique profile is required or whether this can be achieved with existing profiles

**Comment by ym1906** [comment]
Note to future reader: this still needs doing!

**Comment by chris-ashe** [comment]
Related issue #3263 
Can hopefully do this with the refactor and docs
