### ISSUE TITLE
Consolidate divertor heat load models

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1833]
In GitLab by @j-a-foster on Apr 20, 2023, 13:09

The `divwade` model needs to be made available for all aspect ratios, currently it's only available for STs.

It would make sense for all divertor heat load models to be called from the same switch `i_hldiv` so this would require adding the Kallenbach model into `divertor.py` and adding an option for it to the switch.

**Comment by j-a-foster** [comment]
I believe the first part of this issue has already been completed. The `divwade` model is called if `i_hldv == 2`, independently of the type of device/aspect ratio.

**Comment by j-a-foster** [comment]
The Kallenbach model has been removed from PROCESS and isn't being reintroduced until open source hydrogenic data can be found. The rest of this issue has already been completed so closing.
