### ISSUE TITLE
VaryRun bounds do not consider IN.DAT variables

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1859]
In GitLab by @timothy-nunn on May 24, 2023, 11:37

`process_funcs.get_variable_range` uses the bounds in the dicts :sick: and does not appear to consider bounds provided in the IN.DAT file

**Comment by timothy-nunn** [comment]
This issue was fixed via a Gitlab MR in July 2023, the issue was just never closed
