### ISSUE TITLE
Normalised objective function behaving weirdly

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1870]
In GitLab by @kj5248 on May 31, 2023, 14:23

Inconstistent behaviour of (norm_objf) in output file in relation to objective function.  For example:
```
 Normalised objective function                                            (norm_objf)              -1.426E-04  OP 
```
but 
```
 Net electric power output(MW)                                            (pnetelmw.)                 -12.026  OP 
```
whereas the normalised objective function in the example considered here should be 
```
    case (17)  !  net electrical output
       fc = sgn * pnetelmw / 500.0d0

```
where `sgn` is the sign of `minmax`:
```
    !  If sgn is -1 the value of fc will be maximised
    !  If sgn is +1 the value of fc will be minimised
```
The value should be -(-12)/500 = 0.024, not -1.426E-04.

**Comment by timothy-nunn** [comment]
I have tested this using the "path" of the solver on an input file maximising net electric.

I have observed the same behaviour. Where the normalised net electric does not agree with the net electric in the MFILE.

Printing out value of `pnetelmw` when calling `funfom` provides a value that can be different from the MFILE:

| Printed in `funfom` | Output in MFILE |
| ------------------- | ---------------- |
| 394.77803591421662 | 394.78 |
| 0.017754112447730123 | -54.325 |
| 95.995834335900213 | 95.996 |
| 129.77657285970724 | 129.78 |
| 143.51298186912720 | 143.51 |
| 161.38412390533540 | 161.38 |

**Comment by jmorris-uk** [comment]
I agree with Michael that negative net electric values are physically meaningful and should be allowed. Similarly agree that it should be accompanied by a clear warning somewhere in the output.

**Comment by timothy-nunn** [comment]
We already warn about negative net electric as follows:

```python
if heat_transport_variables.pnetelmw < 0:
            po.ocmmnt(
                self.outfile, "WARNING: Calculated net electric power is negative"
            )
            po.ocmmnt(
                self.outfile, "--------------------------------------------------"
            )
```

Therefore, I will just remove the scaling
