### ISSUE TITLE
Division by zero in superconductor calculation

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1871]
In GitLab by @mkovari on May 31, 2023, 15:19

We have had a non-fatal division by zero error in this line in function `superconpf` in pfcoil.py:
```python
            rcv.copperaoh_m2 = ioheof / (pfv.awpoh * (1.0 - pfv.vfohc) * pfv.fcuohsu)
```
The variable `awpoh` is initialised to zero in pfcoil_variables.f90, and the line of code above is called before the correct value is calculated.  

The correct calculation of `awpoh` is in function `ohcalc` in pfcoil.py:
```python
        # Non-steel cross-sectional area
        pfv.awpoh = pfv.areaoh - areaspf
```

ohcalc is first called in line 732 inside function `pfcoil`:
```python
        # Find Central Solenoid information
        if bv.iohcl != 0:
            self.ohcalc()
```

but superconpf is first called in line 627 inside the same function:
```python
                # Allowable current density (for superconducting coils)

                if pfv.ipfres == 0:
                    bmax = max(abs(pfv.bpf[i]), abs(pf.bpf2[i]))
                    pfv.rjpfalw[i], jstrand, jsc, tmarg = self.superconpf(
```

**Comment by mkovari** [comment]
I *think* that this function call can be moved from where it is now:
https://github.com/ukaea/PROCESS/blob/b8c0a3d2259b3c8541011960f6ae3c405274da6d/process/pfcoil.py#L623-L638

to a bit lower down, immediately after line 733:
```python
        # Find Central Solenoid information
        if bv.iohcl != 0:
            self.ohcalc()
```
