### ISSUE TITLE
Tool for analysis Monte Carlo Uncertainty Quantification Results

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1873]
In GitLab by @ym1906  on Jun 2, 2023, 14:29

Develop a tool which can calculate sensitivity indices for MC runs of PROCESS.
- This tool can can plot the indices and their confidence levels.
- It can perform a convergence study to allow the user to evaluate whether the indices are converging.
- It can find all the output parameters which have been influenced by the input parameters (to a significant level).

**Comment by ym1906** [comment]
This is an issue I created at the beginning of my work on UQ. I have created such a tool, but I decided to remove it from the PROCESS repository  and create a separate one for it as it its own application, and there were conflicting requirements.  I think this work will remain separate, as an application of PROCESS, and I don't foresee trying to merge the work back into PROCESS. Therefore I will close this issue.
