### ISSUE TITLE
WIP: Resolve "Costing superconductors in all coils using $/kAm rather than $/kg" - [opened]

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#2294]
In GitLab by @schislet on Apr 3, 2021, 12:09

_Merges 1037-costing-superconductors-in-all-coils-using-kam-rather-than-kg -> develop_

Closes #1037

**Comment by j-a-foster** [comment]
This was taken care of in [this PR](https://github.com/ukaea/PROCESS/pull/3272) so I think this can just be closed.
