### ISSUE TITLE
ndscan tools library updates - low priority

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#277]
In GitLab by @hlux on Apr 24, 2015, 14:24

Whenever you have the time, port the netcdf library for the ndscan tools to the netcdf library that James Edwards has written, as this should be the default for the future.

In that process, clean up the ndscanconfig class in general. As well as the visualisation tool. (Probably get rid of the slices or make them work properly?)

**Comment by ym1906** [comment]
@jonmaddock Is any of this code still relevant? There is no netcdf library any more. It looks like ndscan is an old tool for 2d parameter scans, which are now covered by scans.py. 

Is there still a use for the NdScanConfig at all in PROCESS?

**Comment by jonmaddock** [comment]
In that case, it may be fine to remove it: I'd probably just check with the group first. It would probably be better to use another tool (e.g. easyVVUQ, Dakota) instead of maintaining this internally.
