### ISSUE TITLE
WIP: Resolve "Tool for analysing Monte Carlo Uncertainty Quantification Results" - [opened]

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#2804]
In GitLab by @ym1906  on Jun 2, 2023, 14:30

_Merges 1872-tool-for-analysis-monte-carlo-uncertainty-quantification-results -> develop_

Edit: Closes #1873 

Script which can produce the below plots from evaluate_uncertainty.py output.

Index values:

![image](https://git.ccfe.ac.uk/process/process/uploads/ea0ce4d201a4be35e08c835c42f70809/image.png)

Sensitivity Indices example:
![image](https://git.ccfe.ac.uk/process/process/uploads/069c62aa667d9d1a85e7769afdbe3765/image.png)

Convergence study example:
![image](https://git.ccfe.ac.uk/process/process/uploads/7a262a582c40f3cccc092ca155f80c25/image.png)

**Comment by ym1906** [comment]
I'm no longer developing this within PROCESS (for now), ask me for details if you are interested!
