### ISSUE TITLE
Bremsstrahlungradiation to include Gaunt factor (low priority)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#283]
In GitLab by @hlux on May 7, 2015, 09:37

Thomas Puetterich suggested to update our Bremsstrahlungs calculation using a prescription for the Gaunt-factor as he thinks it will make a significant difference. This is currently low priority as the only two points affected by this are our output of the Bremsstrahlung power and the high T extrapolation (T_e > 100 keV) of the ADAS data. For the rest of the radiation treatment we are using the ADAS data, which is taking all quantum-mechanical and other effects into account.

**Comment by ajpearcey** [comment]
If the Bremsstrahlung radiation is incorrect I suggest we remove it. See issue #1231.
