### ISSUE TITLE
Regression test reference overwriting doesn't work

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#2843]
I ran the regression test with `pytest -k regression --reg-tolerance=0` and got 609 failures. I then overwrote the references with `pytest -k regression --overwrite`, which successfully wrote new reference files. I then ran `pytest -k regression --reg-tolerance=0` again, but still got 609 failures. I expect it to pass.

This either means that the regression test is nondeterministic, or there's some problem with overwriting the regression tests.

**Comment by jonmaddock** [comment]
We might have a non-determinacy problem.
Locally, I did a completely fresh cmake install (non-editable), then ran `pytest -k regression --reg-tolerance=0`:
1st run: pass
2nd run: fail
3rd run: pass
4th run: pass

cmake again:
pass
fail
pass
pass

pip install -e .
pass
pass
fail
pass

pip install -e .
fail
fail
fail
pass

Something's not right. I also noticed that when merging #2841, only the 0% regression test was failing on the branch, but when the workflow ran on main, the 5% test failed too. Locally, they can both pass or fail. There appear to only be 2 states, however: 0% pass or fail with 609 diffs, 5% pass or fail with 4 diffs. The 4 diffs are:

```
WARNING  scenario:scenario.py:223 Variable                     Ref             New        Diff (%)
WARNING  scenario:scenario.py:226 ------------------------------------------------------------
WARNING  scenario:scenario.py:229 auxiliary_cd            1.85e+04               0         -100.00
WARNING  scenario:scenario.py:229 faccd                    0.00111               0         -100.00
WARNING  scenario:scenario.py:229 n_cycle                      122             232           90.09
WARNING  scenario:scenario.py:229 pcurrentdrivemw            0.398               0         -100.00
```
As you can see, rather surprising new values. Perhaps this is a clue?

**Comment by timothy-nunn** [comment]
Non determinism appears to be coming from the OSQP solver.

I have recreated the problem at .

We see the following verbose logs for sequential solutions of the same initial problem. The first is for a solution that would cause our regression tests to fail, the second is for a solution that would cause our regression tests to pass.

> ===============================================================================
                                     CVXPY                                     
                                     v1.3.2                                    
===============================================================================
(CVXPY) Aug 14 12:23:39 PM: Your problem has 45 variables, 3 constraints, and 0 parameters.
(CVXPY) Aug 14 12:23:39 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 14 12:23:39 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 14 12:23:39 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Compiling problem (target solver=OSQP).
(CVXPY) Aug 14 12:23:39 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Aug 14 12:23:39 PM: Applying reduction CvxAttr2Constr
(CVXPY) Aug 14 12:23:39 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Aug 14 12:23:39 PM: Applying reduction QpMatrixStuffing
(CVXPY) Aug 14 12:23:39 PM: Applying reduction OSQP
(CVXPY) Aug 14 12:23:39 PM: Finished problem compilation (took 2.983e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Invoking solver OSQP  to obtain a solution.
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 45, constraints m = 116
          nnz(P) + nnz(A) = 1351
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-01,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1  -6.9544e-02   1.90e-01   5.14e+00   1.00e-01   5.53e-04s
  50   4.4020e-04   1.63e-04   1.64e-02   3.82e+00   1.03e-03s

status:               solved
solution polish:      unsuccessful
number of iterations: 50
optimal objective:    0.0004
run time:             1.66e-03s
optimal rho estimate: 4.85e+00

-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Problem status: optimal
(CVXPY) Aug 14 12:23:39 PM: Optimal value: 1.600e+00
(CVXPY) Aug 14 12:23:39 PM: Compilation took 2.983e-02 seconds
(CVXPY) Aug 14 12:23:39 PM: Solver (including time spent in interface) took 5.232e-03 seconds
===============================================================================
                                     CVXPY                                     
                                     v1.3.2                                    
===============================================================================
(CVXPY) Aug 14 12:23:39 PM: Your problem has 45 variables, 3 constraints, and 0 parameters.
(CVXPY) Aug 14 12:23:39 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 14 12:23:39 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 14 12:23:39 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Compiling problem (target solver=OSQP).
(CVXPY) Aug 14 12:23:39 PM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Aug 14 12:23:39 PM: Applying reduction CvxAttr2Constr
(CVXPY) Aug 14 12:23:39 PM: Applying reduction Qp2SymbolicQp
(CVXPY) Aug 14 12:23:39 PM: Applying reduction QpMatrixStuffing
(CVXPY) Aug 14 12:23:39 PM: Applying reduction OSQP
(CVXPY) Aug 14 12:23:39 PM: Finished problem compilation (took 2.316e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Invoking solver OSQP  to obtain a solution.
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 45, constraints m = 116
          nnz(P) + nnz(A) = 1351
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-01,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1  -6.9544e-02   1.90e-01   5.14e+00   1.00e-01   9.78e-04s
  75   1.6778e-03   8.46e-04   2.21e-02   6.14e+00   2.07e-03s
plsh   1.5627e-05   2.52e-04   2.14e-04   --------   2.61e-03s

status:               solved
solution polish:      successful
number of iterations: 75
optimal objective:    0.0000
run time:             2.61e-03s
optimal rho estimate: 1.35e+01

-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Aug 14 12:23:39 PM: Problem status: optimal
(CVXPY) Aug 14 12:23:39 PM: Optimal value: 1.600e+00
(CVXPY) Aug 14 12:23:39 PM: Compilation took 2.316e-02 seconds
(CVXPY) Aug 14 12:23:39 PM: Solver (including time spent in interface) took 9.268e-03 seconds
equals_pass6 = 1, equals_fail6 = 40, other = 0

**Comment by timothy-nunn** [comment]
Suggestions in https://github.com/osqp/osqp-python/issues/116 fix this issue in my recreation of the issue (https://github.com/timothy-nunn/cvxpy-non-determinism).
