### ISSUE TITLE
Update README link locations

### ISSUE THREAD

**Issue by timothy-nunn** [ukaea/PROCESS#2855]
README links still point at our GitLab pages.

**Comment by rkemb** [comment]
Docker and Singularity installation instruction links point to git.ccfe.ac.uk

**Comment by timothy-nunn** [comment]
@jmorris-uk I think mkdocs makes the massive margins, so I will have a little look into that. For now, I have updated the table styling to make it a bit easier to use.

![image](https://github.com/ukaea/PROCESS/assets/75321887/394badd6-1785-4f58-b4e8-41f91cb2ac03)
