### ISSUE TITLE
Decide on future of the changelog

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#2930]
As discussed in #2895, the changelog may had had its day. We need to decide on how we want to communicate changes through our releases (using github's automatic release notes feature, for example), and remove anything associated with the changelog. It would be good to check out the best practice for this, and make sure that we're doing a good job of communicating our changes to our users.

**Comment by timothy-nunn** [comment]
@clmould lets have a chat about this Wednesday to see whether you found it useful when onboarding. We can also ask around the group to see if anyone has any strong opinions.

**Comment by clmould** [comment]
We discussed this and there's no value in keeping the changelog as the changes are shown in the releases
