### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#2950]
It appears that the build fails when using Python 3.11 (numpy-related). We should obviously get this to work. This is related to sorting out our dependency strategy #1527.

**Comment by timothy-nunn** [comment]
Cannot yet support 3.12 because of a similar error as seen in: https://github.com/numpy/numpy/issues/24874

Unclear as yet whether we will need to rewrite our build system or if f2py will fix this? I get the impression I will need to rewrite our build at some point :(
