### ISSUE TITLE
Availability model: discussion

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#297]
In GitLab by @mkovari on May 18, 2015, 13:49

The new availability model is working, but as yet it doesn't really depend much on the design, as was intended.  Consequently constraint 61 (Minimum availability value) doesn't really work very well - either the availability is adequate, or it isn't, in which case VMCON will probably fail.

We could add a few iteration variables to rectify this.

**Comment by ajpearcey** [comment]
I recommend that we close this issue and move this to a discussion. The availability constraint (icc=61) is currently not used in either EU-DEMO or STEP. The main point raised in the original issue is still true even with the newer availability models included in process, but we would need to think about how and if we what to modify these to work better with the minimum availability constraint.
