### ISSUE TITLE
TF coil, winding pack and turn structure figures output into plot_proc.

### ISSUE THREAD

**Issue by chris-ashe** [ukaea/PROCESS#2992]
## Description of issue / requirement to address
A good addition to `plot_proc.py` would be able to see the top down build of the TF coil along with the correct winding pack shape and the numbers of turns. This can be complemented by another figure which shows the individual structure of each turn

## Proposed solution
Implement two new plotting functions in `plot_proc.py` that prints the TF and WP turn structure onto a new page in `plot_proc.py`

**Comment by mkovari** [comment]
Hi Chris, you might want to have a look at Issue #603 as well.
