### ISSUE TITLE
[BUG] Error message and ID not matching

### ISSUE THREAD

**Issue by timothy-nunn** [ukaea/PROCESS#3019]
## Describe the bug

Incorrect error messages being shown for a given error ID.

## Evidence
```
 PROCESS status flag:   Errors                                            
 
 ID  LEVEL  MESSAGE
150     2   CHECK: Lower limit of volume averaged electron temperature (te) has been raised 
  
243     3   CHECK: Impossible to set the TF coil turn and cable size simultaneously         
  
 PROCESS stopping.
STOP 1
```

## Expected behaviour
```
 PROCESS status flag:   Errors                                            
 
 ID  LEVEL  MESSAGE
150     2   CHECK: Lower limit of volume averaged electron temperature (te) has been raised 
  
243     3   PHYSICS: Predicted plasma driven current is more than upper limit on non-inductive fraction.         
  
 PROCESS stopping.
STOP 1
```

## Environment

- OS: Mac M1
- Version: 3.0.1

## Additional context

@chris-ashe you were right :/ we shouldn't have removed these and should have marked them as obsolete https://github.com/ukaea/PROCESS/pull/3005/files#diff-338097fe08808cafb0e47ce566255e05e842626e515940b66a32a52adf405d04L878

**Comment by jonmaddock** [comment]
I've been experiencing this today, which is causing a previously running solution to error.
```
243, level 2, "PHYSICS: Predicted plasma driven current is more than upper limit on non-inductive fraction."
```
is now replaced by:
```
271, level 3, "CHECK: Impossible to set the TF coil turn and cable size simultaneously"
```
i.e. a level 2 has become a level 3.

@timothy-nunn could you sort this?
