### ISSUE TITLE
[BUG] Indexing error in physics.py

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#3042]
When writing output from `physics.py`, I get the following:

```
  File "/home/jon/code/process/process/physics.py", line 4234, in outplas
    f"Confinement scaling law: { physics_variables.tauscl[physics_variables.isc-1]}",
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```
Could be a non-critical error from the conversion? It throws an exception when writing the output files. Found when running a STEP input file, but could well occur with anything e.g. `large-tokamak`.

**Comment by timothy-nunn** [comment]
The output also needs to be converted from bytes
