### ISSUE TITLE
Review and clarify timings

### ISSUE THREAD

**Issue by j-a-foster** [ukaea/PROCESS#3049]
### Original Issue (#572)
>* [ ]  Redefine the term 'dwell time': any time outside plasma current flat-top.  (TBC: why not any time outside fusion power flat-top?)
>* [ ]  Put in a place-holder for the delay in between ramp-down and pre-charge (currently called `tdwell`), e.g. `t_delay`. Set it to zero.   
>* [ ]  Remove the old timings image from the html output.  
>* [ ]  Replace with an updated image when this is ready.

### Papercut review
After discussion with @mkovari, it's clear that the timings need a deeper review. Some terms are ambiguous in their definitions and/or appear in multiple places in the fusion lexicon e.g. dwell, quench. The above checklist should be replaced with:
* [ ] Redefine 'ramp' as 'pre-charge' when referring to the central solenoid. This is to avoid confusion with plasma current ramp-up.
* [ ] Redefine 'dwell time' to 'delay time' as the time between ramp-down and pre-charge, e.g. `tdwell` -> `t_delay` and set
 `t_delay = 0`.
* [ ] Redefine 'quench' as 'ramp-down' for consistency with 'ramp-up'.
* [ ] Down time, `tdown`, should be redefined to avoid confusion with time when electricity is not being produced.
* [ ] The plot in [Central Solenoid](https://ukaea.github.io/PROCESS/eng-models/central-solenoid/) should be updated to reflect the above changes and perhaps should be moved to its own page on Timings. Should be made clear on plot which of the timings make up `tpulse`, `tdown`, and `tcycle`. Could also be worth including a similar plot for fusion power in the same plot.

**Comment by mkovari** [comment]
I could try to write down some relevant times, with some suggested variable names.  The following phases should all be consecutive and non-overlapping.  I have also marked some points in the cycle, which are identical to those in the OUT.DAT.  I have included the current variable names and their descriptions from `input.f90` in square brackets.

- Start = CS and PF coil currents are all zero
- `precharge` = The CS current ramps from zero to maximum value.  The other PF coils also ramp from zero to their required values. [`tramp` = 'Initial charge time for PF coils (s)']
- BOP = Beginning of Pulse
- `current_ramp_up` = The plasma current ramps up to approx full value.  Auxiliary heating is ON (probably).  [`tohs` = 'Plasma current ramp-up time for current init (s)']  
- EOR = End of Ramp
- `t_fusion_ramp` = The plasma temperature and density rise to the full values.  The CS and other PF coil currents all change steadily.   Auxiliary heating is ON.  ['Heating time after current ramp (s)', formerly `theat`]
- BOF  = Beginning of Flat-top
- `burn_time` = Flat-top duration.  The plasma is approximately steady.  Fusion power and electricity are produced.  The CS and other PF coil currents all change steadily.  Auxiliary heating is ON.  [`tburn` = 'Burn time (s)']
- EOF = End Of Flat-top
- `ramp_down` = The plasma current, density and temperature all ramp down to zero simultaneously.  As a starter for ten we could assume that the CS and PF coil currents also ramp to zero at the same time.  Auxiliary heating is ON (probably). [`tqnch` = 'PF coil shutdown time (s)']
- EOP = End of Pulse (Note that all currents are zero at EOP but not at BOP.)
- `inter_pulse_interval` = CS and PF coil currents are zero - a few minutes may be required to permit vacuum pumping.  May be much longer for an experimental device such as STEP. [`tdwell` = 'Time between burns (s)']

Opinions?  Any comments from a DEMO, STEP or Bluemira perspective? @j-a-foster @jmorris-uk @stuartmuldrew @je-cook

**Comment by je-cook** [comment]
Sounds sensible to me.
In Bluemira, as far as I'm aware, the only pulse related time points we currently have are our equilibria snapshot points that we use in eudemo which are:
- Breakdown
- Start of Flat-top (SOF we call it instead of BOF not that it probably matters)
- End of Flat-top (EOF)
