### ISSUE TITLE
Investigate Scan x failure

### ISSUE THREAD

**Issue by timothy-nunn** [ukaea/PROCESS#3071]
@clmould was trying to run a scan and was getting that certain parts of `x` were outside of the range when starting to run the next scan point. The values outside of the range were `ftmargoh` and `ftburn` which were **not** being scanned and should have been at their default value of `1` at the beginning of the new scan!?

This was running the `scan.ipynb` notebook and was fixed by setting the above f-values to `0.9` in the MFile. Before the values were not being set in the MFile.

**Comment by mkovari** [comment]
Can you give a few more details?  Were `ftmargoh` and `ftburn` iteration variables?  Are you saying they were outside their bounds at the beginning of the next scan point?  Surely all iteration variables are output in the MFile?  Is `x` the solution vector?

**Comment by timothy-nunn** [comment]
Yes both are iteration variables. The rest of the questions I will answer when I look into this on Wednesday

**Comment by timothy-nunn** [comment]
Reset out of bounds iteration variables to their closest bound before the next scan point
