### ISSUE TITLE
Removed unused netcdf code in PROCESS

### ISSUE THREAD

**Issue by clmould** [ukaea/PROCESS#3072]
From looking at my papercut issue #227 and discussing with @timothy-nunn, it has been found that large portions of the code revolving around netcdf is no longer being used. process_netcdf.py is only called within display_uncertainties.py and process_config.py. 
display_uncertainties.py has potentially been superceeded by hdf_to_scatter_plot.py, and so this script may no longer be needed in PROCESS
In process_config.py there is a function called add_results2netcdf which makes use of process_netcdf.py, but this function is not used anywhere in PROCESS, and so perhaps this add_results2netcdf function can be removed
If the netcdf functionality is no longer needed in PROCESS, and if display_uncertainties.py and add_results2netcdf are removed from the code, then nothing in PROCESS will be using the process_netcdf.py script and so this could possibly be removed too

@ajpearcey what are your thoughts about this?

**Comment by timothy-nunn** [comment]
@ym1906 any thoughts too (beyond what you said on Teams to Clair)?

**Comment by ym1906** [comment]
Nothing more to add. I think there's a good case to remove the cdf functions. In my time working on UQ I haven't used them, nor the display_uncertainties.py script.
