### ISSUE TITLE
Once-through model evaluation doesn't produce inequality constraint residuals

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#3087]
The inequality constraint residuals are all 0.0 in the output mfile when performing once-through (non-optimising) runs.

**Comment by timothy-nunn** [comment]
Could this help? https://github.com/ukaea/PROCESS/commit/b3c60b6678532ee0a322c10c4119c4019468a2c5

**Comment by jonmaddock** [comment]
It was actually quite a bit simpler than that, just a silly typo!
