### ISSUE TITLE
Developer group on the documentation is out of date

### ISSUE THREAD

**Issue by ym1906** [ukaea/PROCESS#3112]
The list of developers on the docs could be refreshed to remove old developers and new ones.

**Comment by timothy-nunn** [comment]
Now that we have a proper citation do we need to provide names and contacts beyond those on the README (are these still up-to-date, or should we just list James as a contact?).

**Comment by ym1906** [comment]
I suppose we don't need a list of developers in the docs at all now PROCESS is open source. Perhaps one or two key contacts?

**Comment by timothy-nunn** [comment]
@jmorris-uk @jonmaddock
