### ISSUE TITLE
Add radial build vector to MFILE output

### ISSUE THREAD

**Issue by je-cook** [ukaea/PROCESS#3119]
## Description of issue / requirement to address

Currently in bluemira we use a bit of a hacky solution reading in from the OUT.DAT to reconstruct the radial build vector.
It would we really nice if we could get the radial build vector directly from a PROCESS MFILE.

## Proposed solution

I imagine something like an array with some labels for each created cell. There would be an off by one issue to navigate eg:
```
0     0.1    0.4     0.5 ......
   cs     vv     fw
```

pinging @jonmaddock as we disscussed some wider usecases that could benefit from this.

**Comment by jonmaddock** [comment]
@ajpearcey aside from being a useful output for Bluemira, I wonder if Process could directly benefit from such a vector containing all the radial build information, perhaps simplifying the radial build consistency constraints or similar. Are you aware of any way this could be useful for us internally?

**Comment by ajpearcey** [comment]
it would make the plot_radial_build tool a lot cleaner.

**Comment by athoynilimanew** [comment]
After discussion, we have decided the plan:

1) PROCESS Side: Tim will implement a way to output the ordered dictionary of radial build component to MFILE

2) Bluemira Side: Once the above is done, James will amend the functionality of reading the radial build from MFILE 

@jwscook  @timothy-nunn  @ajpearcey

**Comment by timothy-nunn** [comment]
Output on the process side

```
Radial_build_component_1____ (radial_label(1))_____ "bore"
Radial_build_component_2____ (radial_label(2))_____ "ohcth"
...
Radial_build_cumulative_1____ (radial_cum(1))_____ 1.965
Radial_build_cumulative_2____ (radial_cum(2))_____ "2.545"
```

Aka a flattened ordered dictionary.
