### ISSUE TITLE
New Murari energy confinement scaling

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#312]
In GitLab by @mkovari on Jun 15, 2015, 10:10

Add the new "non-power law" (NPL) Murari energy confinement scaling:

A new approach to the formulation and validation of scaling expressions for plasma confinement in tokamaks  
A Murari, E Peluso, M Gelfusa, I Lupelli, P Gaudio - Nuclear Fusion, 2015  
http://iopscience.iop.org/0029-5515/55/7/073009/article#

The dimensional scaling is given in Table 4, as "NPL".  
There is also a scaling in terms of dimensionless variables (equation 3), referred to as AdNPL.

Check to ensure the correct value is obtained: use ITER, whose parameters are given in the text, and in Figure 4:  

>Using the equations of table 4, the predicted value of the confinement time for ITER (ne = 10.3 10^19 m^−3, κa = 1.70, Ip = 15 MA, R = 6.2 m, P = 87 MW) is about 2.96 seconds to be compared to the 3.6  seconds of the traditional extrapolations obtained with power law scalings (IPB98). 

Figure 4:  B = 5.3 T.

Comments? @rkemp @hlux 

![Capture](http://git.ccfe.ac.uk:8080/uploads/process/process/0d37b92d17/Capture.PNG)

Output when IPB98(y,2) law is used:
```
 Confinement scaling law                    IPB98(y,2)           (H)
 Confinement H factor                        (hfact)                       1.100
 Global energy confinement time (s)          (taueff)                      3.978

 IPB98(y,2)           (H)          3.616                   1.100
 IPB98(y,3)           (H)          3.735                   1.065
 IPB98(y,4)           (H)          3.707                   1.073
 ISS95            (stell)          2.130                   1.867
 ISS04            (stell)          3.730                   1.067
 DS03                 (H)          5.207                   0.764
 Murari et al NPL     (H)          2.615                   1.521
 ```

Output when Murari law is used, with upper bound for hfact=1.521:
```
 Confinement scaling law                    Murari et al NPL     (H)
 Confinement H factor                      (hfact)                       1.521
 Global energy confinement time (s)        (taueff)                      3.978

 IPB98(y,2)           (H)          3.618                   1.100
 IPB98(y,3)           (H)          3.737                   1.065
 IPB98(y,4)           (H)          3.709                   1.073
 ISS95            (stell)          2.131                   1.866
 ISS04            (stell)          3.731                   1.066
 DS03                 (H)          5.209                   0.764
 Murari et al NPL     (H)          2.616                   1.521 
```

I haven't tried running it with upper bound on hfact = 1.1 !!

**Comment by mkovari** [comment]
See a new scaling from Murari: #3980.
