### ISSUE TITLE
Some variable description tables not formatting correctly

### ISSUE THREAD

**Issue by j-a-foster** [ukaea/PROCESS#3125]
Some of the variable descriptions tables are not formatting correctly and overlapping with the table of contents, such as [fwbs_variables](https://ukaea.github.io/PROCESS/vardes/#fwbs_variables). Others have the same problem to varying degrees and it's unclear what is wrong in the generated `vardes.md`.

**Comment by clmould** [comment]
We will be getting rid of the fortran in 2025 so documenting the fortran variables will not be necessary. It will be handled by the Python documentation tool, and so will close the issue.
