### ISSUE TITLE
Incorrect error in winding pack current density constraint.

### ISSUE THREAD

**Issue by ajpearcey** [ukaea/PROCESS#3150]
In constraint 35 for the current density in the winding pack the constraint error is calculated as
```
tmp_err = jwptf - jwptf
```
This is wrong and surely causes the constraint to never be violated? I believe it should be 
```
tmp_err =  jwptf - jwdgpro 
```

**Comment by mkovari** [comment]
That's odd. Surely we would have spotted that previously?  In this output, for example, the reported error is not zero:
https://github.com/ukaea/PROCESS/blob/df04db9a0dbec17f337f23f3762b876cbfaf256c/tests/unit/data/large_tokamak_MFILE.DAT#L173
