### ISSUE TITLE
Automate the tracking jobs

### ISSUE THREAD

**Issue by timothy-nunn** [ukaea/PROCESS#3202]
Currently, the `run-tracking-inputs` runs all of input files for the regression tests and saves the resulting MFile. In general...
* we run `tests/regression/input_files/<name>.IN.DAT`
* and save the resulting mfile as `tracking/<name>_MFILE.DAT`

The `tracking` job then `track`s all of the MFiles into a database (uploads the tracked JSON file and MFile to a Git repository). 

Looking at the `.github/workflows/process.yml`, both of these jobs involve a series of repetition over [input files](https://github.com/ukaea/PROCESS/blob/main/.github/workflows/process.yml#L173-L182) and [MFiles](https://github.com/ukaea/PROCESS/blob/main/.github/workflows/process.yml#L248-L256), respectively. This should be simplified to allow the tracker to automatically handle new input files.

**Comment by timothy-nunn** [comment]
NOTE: what happens if an input file fails?

**Comment by clmould** [comment]
Closed by #3318
