### ISSUE TITLE
Fix stellarator regression test

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#3245]
The stellarator regression test currently doesn't converge, as a result of #3240. This is because the original stellarator solution actually contained violated inequality constraints, which are now required to be satisfied for the solver to converge. Arguably, the original solution wasn't really a solution at all, as it contained violated constraints.

The regression test is currently being skipped until a new solution is found.

**Comment by timothy-nunn** [comment]
Will need to add tracking job back too #3246
