### ISSUE TITLE
Warn rather than raise exception when idempotence check fails

### ISSUE THREAD

**Issue by j-a-foster** [ukaea/PROCESS#3249]
Two separate examples of the new idempotence check failing on the second point of a scan have been reported by @j-a-foster and @chris-ashe. The message reported in the terminal is: `RuntimeError: Model evaluations at the current optimisation parameter vector don't produce idempotent values in the final output.`

Given that this is happening identically for two separate scans using different input files, it would be helpful to understand what about them is causing the failure and/or having an option to continue the scan even if the idempotence check fails.

It's worth noting that the scan continues just fine if the error message is commented out of the code.

**Comment by chris-ashe** [comment]
If the `RaiseException` error is removed then PROCESS is able to fully complete the full scan. Though the output MFILE is cutoff off at the iteration variables for the first point. Therefore their is no usable output

**Comment by mkovari** [comment]
Funnily the error only occurs in `call_models_and_write_output`, not in `call_models`, if I understand your description, since the error messages are different.

**Comment by jonmaddock** [comment]
I have recently experienced this with a spherical tokamak input file. I've created a diagnostic that enables the non-idempotent (i.e. still varying) variables to be identified; they are the cause of this error. It would also be a good idea to allow this exception to be bypassed (like @chris-ashe did); maybe turn it into a warning?
