### ISSUE TITLE
Update the fusion reactions section of the plasma docs to full account for all models and details

### ISSUE THREAD

**Issue by chris-ashe** [ukaea/PROCESS#3260]
The fusion reactions section of the docs needs updated to include and fully explain all new models and variables.

## Questions

1. Bosch-Hale presents a parameterised form for the branching ratio for the D-D products, should this be added in since PROCESS will always assume 50-50?
2. The Bosch-Hale method does not include reactions from T-T and 3He-3He, could these be added in?
3. ~~There still seems to be some legacy calculations still used in the main code found in `physics_functions.f90`. Should these be converted to Python?~~.  Being done by #3338 
4. Some reaction rates may not all be plotted to the output files, this should be checked

**Comment by mkovari** [comment]
This paper [Štancar](https://iopscience.iop.org/article/10.1088/1741-4326/ad0310/meta) seems to say that TT is not negligible.  I don't think it's a big deal, though.

I was not aware that the branching ratio for DD is not fixed.  What does it depend on?
