### ISSUE TITLE
Create remaining integration tests for `process.io` subpackage

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#3267]
Some modules within the `process.io` subpackage are not yet tested: these are the modules that deal with manipulating, processing or visualising Process's input/output files. Before the Python data structure work commences, it would be advantageous to write tests for any of these modules that will still be required in some form after the Python conversion work. Which modules to test should be decided, and then the integration tests implemented.

**Comment by clmould** [comment]
I have looked to see if the scripts in the `process/io` subpackage have tests or not. Here is a summary:

- `configuration.py` no need to test
- `in_dat.py` no need to add a test for this as the IN.DAT file format will be removed in the future
- `mfile2dict.py` this already has a test
- `mfile_comparison.py` no need to add a test for this as the MFILE.DAT file format will be removed in the future
- `mfile.py` no need to add a test for this as the MFILE.DAT file format will be removed in the future
- `mfile_to_csv.py` this is already tested
- `obsolete_vars.py` no need to test as this just contains a dictionary of obsolete variables and their replacements/helpful messages
- `plot_proc.py` this already has a test
- `plot_radial_build.py` this already has a test
- `plot_sankey.py` this already has a test
- `plot_scans.py` this already has a test
- `plot_solutions.py` this already has a test
- `process_config.py` no need to test
- `process_funcs.py` no need to test
- `python_fortran_dicts.py` no need to test
- `sankey_funcs.py` this is indirectly tested through `test_plot_sankey.py`
- `variable_metadata.py` no need to test 

This means that the `process/io` subpackage is currently adequately tested and so no more tests need to be added, so will close this issue.
