### ISSUE TITLE
[BUG] KeyError occurs for plotting summary in example.ipynb

### ISSUE THREAD

**Issue by JaeBeom1019** [ukaea/PROCESS#3284]
Hello,

I recently downloaded PROCESS and ran the example file, but I encountered an error in the  [example file](https://github.com/ukaea/PROCESS/blob/main/examples/examples.ipynb).

While running the example file, the basic run results in my notebook matched the expected results. However, when I tried to plot the summary, I encountered a KeyError, which was highlighted in red with four lines.

![image](https://github.com/user-attachments/assets/6ca9220f-bbf9-44e9-95a1-f51a5522fe54)

I would greatly appreciate any guidance you could provide to resolve this issue.

Thank you!

**Comment by clmould** [comment]
Hi @JaeBeom1019 
 
Thank you for reporting this issue. I believe it should be fixed by #3285. Please get in contact again with any other issues or comments, and thank you for your interest in PROCESS!
