### ISSUE TITLE
[BUG] Some question for VaryRun and Scan in example files.

### ISSUE THREAD

**Issue by JaeBeom1019** [ukaea/PROCESS#3301]
Hello!

1. I understand there may be some challenges in returning the current working directory (CWD). However, I am curious if the Jupyter cell for VaryRun is currently unavailable.

2. It appears that there might be a missing line for VaryRun in **examples.ipynb.** Could this omission be intentional to indicate that VaryRun is not yet available?
```
cwd = Path.cwd()

vary_run = VaryRun(str(temp_input_path))
vary_run.run() # Added line
os.chdir(cwd)

temp_dir.cleanup()
```
3. The Jupyter kernel crashes when running **scan.ipynb.** Could you please verify if this functionality is currently supported?
```
from process.main import SingleRun
from pathlib import Path


data_dir = Path("data")
input_name = data_dir / "scan_example_file_IN.DAT"
single_run = SingleRun(str(input_name), solver="vmcon_bounded") #Error occurs in here
single_run.run()
```

**Comment by timothy-nunn** [comment]
Hi @JaeBeom1019,

Could you please provide a trace of the error for point 3?

Cheers,
Tim

**Comment by JaeBeom1019** [comment]
Hi @timothy-nunn !

Below is error log in terminal, not in jupyter notebook (kernel dies with no error message in jupyter cell)

> [I 2024-09-05 18:44:09.452 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
> [W 2024-09-05 18:44:09.453 ServerApp] kernel f1db63fa-e492-42b1-a78b-e6988739f49b restarted
> [I 2024-09-05 18:44:09.461 ServerApp] Starting buffering for f1db63fa-e492-42b1-a78b-e6988739f49b:e522d998-3106-46ff-b241-ce0c2849b176
> [I 2024-09-05 18:44:09.795 ServerApp] Connecting to kernel f1db63fa-e492-42b1-a78b-e6988739f49b.
> [I 2024-09-05 18:44:09.795 ServerApp] Restoring connection for f1db63fa-e492-42b1-a78b-e6988739f49b:e522d998-3106-46ff-b241-ce0c2849b176

I guess error 3 occurs when the real directory path pass into Single class, not using **TemporaryDirectory**.
Why I think likewise is because the error has fixed when I tried 

```
from process.main import SingleRun
from pathlib import Path

script_dir = Path("__file__").parent.resolve()
input_rel = script_dir / "data/scan_example_file_IN.DAT"
temp_dir, temp_input_path = copy_to_temp_dir(input_rel)

single_run = SingleRun(str(temp_input_path), solver="vmcon_bounded")
single_run.run()
```

while still

`single_run = SingleRun("_real path_", solver="vmcon_bounded")`

still kill kernel.




Howerver I encountered for a new problem about plotting scan results.

```
from process.main import SingleRun
from pathlib import Path

script_dir = Path("__file__").parent.resolve()
input_rel = script_dir / "data/scan_example_file_IN.DAT"
temp_dir, temp_input_path = copy_to_temp_dir(input_rel)

single_run = SingleRun(str(temp_input_path), solver="vmcon_bounded")
single_run.run()

from process.io import plot_scans

plot_scans.main(
    args=[
        "-f",
        str(temp_input_path),
        "-yv",
        "thwcndut",
        "--outputdir",
        str(temp_input_path.parent),
    ]
)

```

with error message below.

> --------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[13], line 17
>      11 from process.io import plot_scans
>      13 # Define working directory relative to project dir and input file name
>      14 # input_rel = script_dir / "data/scan_MFILE.DAT"
>      15 # temp_dir, temp_input_path = copy_to_temp_dir(input_rel)
> ---> 17 plot_scans.main(
>      18     args=[
>      19         "-f",
>      20         str(temp_input_path),
>      21         "-yv",
>      22         "thwcndut",
>      23         "--outputdir",
>      24         str(temp_input_path.parent),
>      25     ]
>      26 )
>      28 #temp_dir.cleanup()
> 
> File ~/.local/lib/python3.10/site-packages/process/io/plot_scans.py:297, in main(args)
>     295 m_file = mf.MFile(filename=input_files[-1])
>     296 nsweep_ref = int(m_file.data["nsweep"].get_scan(-1))
> --> 297 scan_var_name = nsweep_dict[nsweep_ref]
>     298 # Get the eventual second scan variable
>     299 nsweep_2_ref = int(0)
> 
> KeyError: 0


So could you tell me **why this plotting error occurs** and how to call Single class with real path not with Temporarydirectory?
And I would be grateful if you can show me the code of how to plot the scan result. I think the scan result may be restored at Temporarydirectory, but I cannot find how to plot this data.

Thank you always!

**Comment by JaeBeom1019** [comment]
In Addition this is a error log when I tried to run Varyrun with below code. (for error 1, 2)

[process.log](https://github.com/user-attachments/files/16887824/process.log)

```
cwd = Path.cwd()

vary_run = VaryRun(str(temp_input_path))
vary_run.run() # Added line
os.chdir(cwd)

temp_dir.cleanup()
```

**Comment by timothy-nunn** [comment]
Hi @JaeBeom1019,

To help with my investigation, could you clarify a couple of things:
1. What system are you running on (Linux, MacOS) and what version?
2. How are you running the notebooks? Via VSCode or a Jupyterserver etc. 
3. Have you installed the latest version of PROCESS?

To install the latest version of PROCESS (from the root directory of the PROCESS repository):
```bash
git checkout main
git pull
rm -r build/
cmake -S. -Bbuild
cmake --build build
```

**Comment by JaeBeom1019** [comment]
Hello @timothy-nunn 

I'm running on **Ubuntu_22.04** with **WSL**, using **jupyter notebook.**
And I'm currently using the latest version.
Same errors occured when I re-intalled PROCESS

Thanks!

**Comment by timothy-nunn** [comment]
Hi @JaeBeom1019,

I am still having an issue recreating the kernel crash issue. Could you confirm if _anything_ happens in the cell?

For example, I get:

![image](https://github.com/user-attachments/assets/79b02cfd-f444-41b1-aeb2-9313a763fd8d)

Maybe you could send a screenshot that shows the kernel dying.

Also have you changed the input file at all? If so, could you attach it?

Cheers,
Tim

**Comment by JaeBeom1019** [comment]
Hi @timothy-nunn 

1. There's no event in the cell and here is the captured one.

![image](https://github.com/user-attachments/assets/eeffd8ff-df22-444d-b7a5-3316bc743291)



2. And I also used IN.DAT same with the uploaded one.
Since git does not support uploading IN.DAT file, I uploaded input file with .zip file.
[scan_example_file_IN.zip](https://github.com/user-attachments/files/16914106/scan_example_file_IN.zip)



3. Also I attached **pytest** error log below

> ================================================= test session starts ==================================================platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
> rootdir: /mnt/c/Users/조재범/Desktop/Program/Program/PROCESS
> plugins: cov-5.0.0, xdist-3.6.1, anyio-4.4.0
> collected 512 items / 1 skipped
> 
> tests/integration/test_blanket_library_int.py .......                                                            [  1%]
> tests/integration/test_costs_bar.py .                                                                            [  1%]
> tests/integration/test_costs_pie.py .                                                                            [  1%]
> tests/integration/test_examples.py .F.F                                                                          [  2%]
> tests/integration/test_main_int.py .....                                                                         [  3%]
> tests/integration/test_mfile_to_csv.py .                                                                         [  3%]
> tests/integration/test_pfcoil_int.py ..........                                                                  [  5%]
> tests/integration/test_plot_proc.py ..                                                                           [  6%]
> tests/integration/test_plot_radial_build.py .                                                                    [  6%]
> tests/integration/test_plot_sankey.py .                                                                          [  6%]
> tests/integration/test_plot_scans.py ...                                                                         [  7%]
> tests/integration/test_plot_solutions.py .                                                                       [  7%]
> tests/integration/test_plot_stress_tf.py .                                                                       [  7%]
> tests/integration/test_solver.py .                                                                               [  7%]
> tests/integration/test_utilities.py ..                                                                           [  8%]
> tests/integration/test_vmcon.py ..s..                                                                            [  8%]
> tests/integration/test_write_new_in_dat.py .                                                                     [  9%]
> tests/regression/test_process_input_files.py ...s.                                                               [ 10%]
> tests/unit/test_availability.py .....................                                                            [ 14%]
> tests/unit/test_blanket_library.py ......                                                                        [ 15%]
> tests/unit/test_build.py ......                                                                                  [ 16%]
> tests/unit/test_buildings.py ....                                                                                [ 17%]
> tests/unit/test_ccfe_hcpb.py ...................                                                                 [ 21%]
> tests/unit/test_coolprop_interface.py ...                                                                        [ 21%]
> tests/unit/test_costs_1990.py .................................................................................. [ 37%]
> ...................                                                                                              [ 41%]
> tests/unit/test_costs_2015.py ................                                                                   [ 44%]
> tests/unit/test_cs_fatigue.py ...                                                                                [ 45%]
> tests/unit/test_current_drive.py ...                                                                             [ 45%]
> tests/unit/test_dcll.py ....                                                                                     [ 46%]
> tests/unit/test_divertor.py .......                                                                              [ 47%]
> tests/unit/test_fw.py ..                                                                                         [ 48%]
> tests/unit/test_ife.py .                                                                                         [ 48%]
> tests/unit/test_impurity_radiation.py ...                                                                        [ 49%]
> tests/unit/test_input.py ..............................                                                          [ 54%]
> tests/unit/test_main.py .....Fatal Python error: Segmentation fault
> 
> Thread 0x00007f3e6b7fe640 (most recent call first):
>   File "/usr/lib/python3.10/threading.py", line 324 in wait
>   File "/usr/lib/python3.10/threading.py", line 607 in wait
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/jupyter_client/channels.py", line 130 in _async_run
>   File "/usr/lib/python3.10/asyncio/events.py", line 80 in _run
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 1909 in _run_once
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 603 in run_forever
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 636 in run_until_complete
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/jupyter_client/channels.py", line 149 in run
>   File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
>   File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap
> 
> Thread 0x00007f3e7a083640 (most recent call first):
>   File "/usr/lib/python3.10/threading.py", line 324 in wait
>   File "/usr/lib/python3.10/threading.py", line 607 in wait
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/jupyter_client/channels.py", line 130 in _async_run
>   File "/usr/lib/python3.10/asyncio/events.py", line 80 in _run
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 1909 in _run_once
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 603 in run_forever
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 636 in run_until_complete
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/jupyter_client/channels.py", line 149 in run
>   File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
>   File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap
> 
> Current thread 0x00007f3f038be000 (most recent call first):
>   File "/usr/lib/python3.10/pathlib.py", line 611 in _format_parsed_parts
>   File "/usr/lib/python3.10/pathlib.py", line 627 in __str__
>   File "/usr/lib/python3.10/pathlib.py", line 632 in __fspath__
>   File "/usr/lib/python3.10/pathlib.py", line 1097 in stat
>   File "/usr/lib/python3.10/pathlib.py", line 1290 in exists
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/_code/code.py", line 97 in path
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/python.py", line 1635 in _traceback_filter
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/_code/code.py", line 971 in repr_traceback
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/_code/code.py", line 1058 in repr_excinfo
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/_code/code.py", line 690 in getrepr
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/nodes.py", line 456 in _repr_failure_py
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/python.py", line 1669 in repr_failure
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/reports.py", line 376 in from_item_and_call
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/runner.py", line 368 in pytest_runtest_makereport
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/runner.py", line 244 in call_and_report
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/runner.py", line 132 in runtestprotocol
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/main.py", line 362 in pytest_runtestloop
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/main.py", line 337 in _main
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/main.py", line 283 in wrap_session
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 175 in main
>   File "/home/aspire1019/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201 in console_main
>   File "/home/aspire1019/.local/bin/pytest", line 8 in <module>
> 
> Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, process.fortran, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, numexpr.interpreter, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, zmq.backend.cython._zmq, tornado.speedups, fontTools.misc.bezierTools, fontTools.varLib.iup, cython.cimports.libc.math, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ellip_harm_2, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct, _cvxcore, scipy.signal._sigtools, scipy._lib._uarray._uarray, scipy.signal._max_len_seq_inner, scipy.signal._upfirdn_apply, scipy.signal._spline, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, scipy.signal._sosfilt, scipy.signal._spectral, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, scipy.signal._peak_finding_utils, _ecos, _scs_direct, osqp._osqp, CoolProp._constants, CoolProp.CoolProp, yaml._yaml, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, scipy.cluster._vq, scipy.cluster._hierarchy, scipy.cluster._optimal_leaf_ordering, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, netifaces, _cffi_backend, matplotlib._ttconv, PIL._imagingmath (total: 180)
> Segmentation fault

I hope these lines would be helpful to fix the error.


Thank you!

**Comment by timothy-nunn** [comment]
Hi @JaeBeom1019,

I have found a way to replicate the issue of the kernel dying.

By putting my PROCESS in a directory using Korean characters my kernel too died (/home/ubuntu/조재범/PROCESS). 

I will look into a solution for this and keep you updated. In the meantime, is it possible to create a WSL user with ASCII character name?

Tim
