### ISSUE TITLE
[BUG] The error parameters are not printed

### ISSUE THREAD

**Issue by mkovari** [ukaea/PROCESS#3316]
In the OUT.DAT, error 76 is displayed, but the relevant parameters are not printed.

## Steps to reproduce

Run IN.DAT attached. 
[Pirizad IN.DAT.txt](https://github.com/user-attachments/files/17013776/Pirizad.IN.DAT.txt)

## Expected behaviour

The code sends the following local variables to the error routine, so I expect them to be output in OUT.DAT:
```python
        if np.isnan(aj) or np.isnan(alfpnw) or np.isnan(alftnw) or aj < 0:
            error_handling.fdiags[0] = aj
            error_handling.fdiags[1] = alfpnw
            error_handling.fdiags[2] = alftnw
            error_handling.fdiags[3] = aj

            error_handling.report_error(76)
```

## Evidence
OUT>DAT:
```
 76     3   BOOTSTRAP_FRACTION_WILSON: Illegal profile value found                          
 Final error identifier                                                   (error_id)                       76     
```
## Environment

- OS: Not known
- Version: 
   3.1.0   Release Date :: 2024-03-21
   Tag No. : v3.1.0
    Branch : HEAD

## Additional context

I haven't run this myself - it's a query from outside.
Any ideas @timothy-nunn @jonmaddock @chris-ashe ?

**Comment by chris-ashe** [comment]
Looking at the source for the Wilson model in AEA FUS 172, I am struggling to see why these constraints have been added for the profiles

**Comment by mkovari** [comment]
Well you don't generally want negative parameters?

**Comment by mkovari** [comment]
@clmould Did you not create a branch for this?

**Comment by mkovari** [comment]
The diagnostic parameters now appear in the OUT.DAT:
![image](https://github.com/user-attachments/assets/272ca713-8bd5-4006-a7d5-e8478de740b1)
