### ISSUE TITLE
Implement suite of new bootstrap current scalings

### ISSUE THREAD

**Issue by chris-ashe** [ukaea/PROCESS#3344]
While doing work on #3263, I came across several papers giving lists of bootstrap current scalings not yet implemented in `PROCESS` though could easily be.

From the paper by Tobias Hartman there is this list (https://inis.iaea.org/search/search.aspx?orig_q=RN:45031642):

![image](https://github.com/user-attachments/assets/f12a0219-4933-4cba-a663-d42dffb7d9e3)

- Hoang et al model: https://www.osti.gov/biblio/16442

- Andrade and Ludwig model: https://iopscience.iop.org/article/10.1088/0741-3335/50/6/065001/pdf

- ASC model: https://qedfusion.org/LIB/REPORT/CONF/ACTsyscodedocs/ASC_FED2_Dragojlovic.pdf (Seems to be from Zoran Dragojlovic working on the ARIES programme)

- TOPPER model: **No reference yet**

------------------------

There is also scalings from this paper by Ki. G et.al. (https://doi.org/10.1016/j.fusengdes.2014.07.009)

![image](https://github.com/user-attachments/assets/d89bbc9e-72e5-4103-bbe3-f694370f503f)

- ARIES-SC model: https://www.sciencedirect.com/science/article/pii/S0920379610000414
(Seems to be the same as the ASC model above)

- Andrade model: https://iopscience.iop.org/article/10.1088/0741-3335/50/6/065001/pdf
-(Same as Andrade and Ludwig from above)

**Gi et.al also presents two scalings of their own type**

-----------------------------

There is also scalings from the recently implemented Sakai et.al paper (https://www.sciencedirect.com/science/article/pii/S092037961930818X?via%3Dihub)

![image](https://github.com/user-attachments/assets/fa476c89-14a4-4e2c-b2dd-09fa49ed2086)

**Comment by mkovari** [comment]
Sounds like a great idea, but I would argue that one up-to-date and credible scaling with some thought put into the implementation is better than a dozen scalings that no-one will use.

Note that the Sakai scaling has already been implemented - #3268.
