### ISSUE TITLE
First wall thermohydraulic model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#349]
In GitLab by @mkovari on Nov 26, 2015, 08:43

The first wall calculation (subroutine iterate_fw in hcpb.f90) is very complicated, and causes frequent problems.  I propose to replace it, as described below.

The thickness of the pipe wall sufficient to withstand the pressure is always very small - a fraction of a mm.  In practice thermal stresses, corrosion and manufacturing issues will determine the thickness, so this is now an input. (This is additional to the armour thickness.)
  
The maximum temperature at the front face is calculated, and a constraint is available to limit this temperature.  The first wall channel length affects this, as it determines the flow speed, so it is available as an iteration variable.  Note it is no longer derived from the size and shape of the blanket module.

Strictly speaking since the first wall temperature is not known to start with, the thermal conductivity and heat transfer coefficient are not known.  To get round this the global variable `tpeak` (peak first wall temperature) is now initialised to 873 K.  Its value converges as VMCON converges.  

The LeClaire formula for circular pipes is NOT used.  It gives an unrealistically small temperature differential, as the wall thickness is the same all the way round, and the surface area is bigger than that of a flat wall.  Instead two simple approximations are used:

See attached file.

It would be good to have an input for the reduction in thermal conductivity due to irradiation.
```
afwi /0.008/ : inner radius of inboard first wall/blanket coolant channels OBSO LETE (m)
afwo /0.008/ : inner radius of outboard first wall/blanket coolant channels OBS OLETE (m
fwcoolant /helium/ : first wall coolant (can be different from blanket coolant) 'helium' or 'water' (15/11/27)
fw_wall /0.003/ : wall thickness of first wall coolant channels (m) (15/11/27)
afw /0.006/ : radius of first wall cooling channels (m) (27/11/15)
pitch /0.020/ : pitch of first wall cooling channels (m) (27/11/15)
fwinlet /623/ : inlet temperature of first wall coolant (K) (15/11/27)
fwoutlet /823/ : outlet temperature of first wall coolant (K) (15/11/27)
fwpressure /15.5e6/ : first wall coolant pressure (Pa) (secondary_cycle>1)
tpeak : peak first wall temperature (K) (15/11/27)
roughness /1e-6/ : first wall channel roughness epsilon (m) (15/11/27)
fw_channel_length /4.0/ : Length of a single first wall channel (all in paralle l) (m) ( (iteration variable 114, useful for constraint equation 39)
peaking_factor /1.0/ : peaking factor for first wall heat loads (15/11/27) (Applied separately to inboard and outboard loads. Applies to both neutron and surface loads.)
blpressure /15.5e6/ : blanket coolant pressure (Pa) (secondary_cycle>1) (15/11/ 27)
inlet_temp /573.0/ : inlet temperature of blanket coolant (K) (secondary_cycle >1) (15/
outlet_temp /823.0/ : outlet temperature of blanket coolant (K) (15/11/27)
    (secondary_cycle>1);
    input if coolwh=1 (helium), calculated if coolwh=2 (water)

coolp /15.5e6/ : blanket coolant pressure (Pa) stellarator ONLY (15/11/27) 
```

[First_wall_geometry_for_PROCESS.docx](http://git.ccfe.ac.uk:8080/process/process/uploads/0e88f4200a069e1565ef7c80e5154960/First_wall_geometry_for_PROCESS.docx)

**Comment by mkovari** [comment]
![Thames_Ansys000](https://github.com/user-attachments/assets/64ad4e4e-9a89-4fde-b002-cd59303ef73c)

![Thames_Ansys002](https://github.com/user-attachments/assets/f5aa7d60-2207-4663-83c9-e834d33c9a05)
