### ISSUE TITLE
Save OUT.DAT in test suite by default

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#358]
In GitLab by @mkovari on Feb 2, 2016, 16:22

At present the test_suite includes the IN.DAT required to make the latest code run (as well as the original ref.IN.DAT), but it does not by default save the new OUT.DAT.  It is important to save this too, in the same folder as IN.DAT, as it will often have new and improved outputs.

**Comment by clmould** [comment]
Will make a decision in issue #3043
