### ISSUE TITLE
Coupling to JINTRAC

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#371]
In GitLab by @mkovari on Apr 14, 2016, 13:57

A utility to link PROCESS with JINTRAC.  This might be written in three stages:
1. Convert a PROCESS output file into a set of JINTRAC input files, and run JINTRAC.    
2. Compare the JINTRAC output to the PROCESS output, to see how consistent they are.   
3. Full incorporation of JINTRAC into the PROCESS optimiser.

For input in the simplest mode JINTRAC requires the following three files, which would normally be created automatically by JAMS ([Jet Application Management System](http://users.euro-fusion.org/pages/data-cmg/jams/index.html)):
1. jetto.in    JETTO input: Fortran namelist
2. jetto.sin   SANCO input: Fortran namelist
3. jetto.ex    Profiles, including initial conditions for q, T, n, etc.  Requires beam deposition profile unless PENCIL is used.  Binary file.

The output from JINTRAC is a ppf file.  You need authorisation to write private PPFs before you can run Jetto. This can be obtained from the dmsd-support help desk. 

JINTRAC (JET INtegrated TRAnsport Code) is a suite of stand-alone codes linked together for integrated simulations. The basic core of JINTRAC is JETTO and SANCO.  ESCO is also required to calculate a plasma equilibrium.   

JETTO is a one-and-a-half-dimensional transport code calculating the evolution of plasma parameters in a time dependent axisymmetric MHD equilibrium configuration.  SANCO is an impurity code.

PENCIL is available for neutral beam simulation.  COCONUT, a combination of JETTO and EDGE2D makes it possible to model the entire plasma including the core, edge transport barrier (ETB) and scrape-off layer (SOL) self-consistently, but this is for advanced users only.  

JINTRAC runs on the JAC system while PROCESS usually runs on the FUSLW system.

Damian King and Luca Garzotti have experience of running JINTRAC for DEMO scenarios.  Elina Militello Asp also has relevant expertise.

**Comment by stuartmuldrew** [comment]
We have been running JETTO based on PROCESS runs and feedback, but this is not an automated procedure.  I think it would be more valuable to couple PROCESS and JETTO within BLUEMIRA.

**Comment by mkovari** [comment]
Seeing the central role that JETTO has played in STEP, I agree.

The coupling of PROCESS and JETTO doesn't have to be within Bluemira, although that would seem a good approach.
@stuartmuldrew
