### ISSUE TITLE
Old first wall temperature model in fw_temp subroutine

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#389]
In GitLab by @jmorris-uk on May 26, 2016, 08:43

Should we remove this model? There are some unused functions and variables in fw_temp. I have separated them out more clearly with comments. But should discuss whether to remove or not.

List of variables not used.
```
thtmet
bfw
viscf
```
Functions no longer called include
```
cosine_term()
smt()
```
There are variables for models A, B and C but they are not separated out when they are defined. The subrouinte needs a bit of TLC.

**Comment by jmorris-uk** [comment]
`thtmet` no longer exists
`bfw` exists in commented out `Model A - LeClaire formula` in `fw.py`
`viscf` no longer exists outside of being a subroutine argument name
`cosine_term()` -- does not exist outside model A
`smt()` -- no longer exists in codebase

On branch will remove Model A from code and remove `bfw` from `pulse_variables.f90`
