### ISSUE TITLE
Use of emult in process

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#405]
In GitLab by @rkemp on Jul 14, 2016, 16:52

I am finding it impossible to tell from the vardes if the old, simple blanket option still exists that allows emult to be set manually.

There are options:
blktmodel /0/ : switch for blanket/tritium breeding model (but see lblnkt):
    = 0 original simple model;
    = 1 KIT model based on a helium-cooled pebble-bed blanket (HCPB) reference design

blkttype /3/ : Switch for blanket type:
    = 1 WCLL; efficiency taken from WP13-DAS08-T02, EFDA_D_2M97B7
    = 2 HCLL; efficiency taken from WP12-DAS08-T01, EFDA_D_2LLNBX
    = 3 HCPB; efficiency taken from WP12-DAS08-T01, EFDA_D_2LLNBX

iblanket /1/ : switch for blanket model:
    = 1 CCFE HCPB model;
    = 2 KIT HCPB model;
    = 3 CCFE HCPB model with Tritium Breeding Ratio calculation

We have multiple redundancy in this and it is not clear which options are actually valid. Could this be tidied up and could someone let me know if the original model does still exist (blktmodel = 0 does not do it)? If not, why not -- it should be preserved for future flexibility and rapid exploration of new blanket options.

**Comment by mkovari** [comment]
Please see #1594 which Clair has just implemented in #3035.
