### ISSUE TITLE
Copper fraction of Bi2212 strand

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#407]
In GitLab by @rkemp on Jul 26, 2016, 16:30

The parameterisation for HTS BI2212 (isumattf = 2) says in the code
"N.B. jcrit returned by bi2212 is the critical current density
         !  in the strand, not just the superconducting portion.
         !  The parameterization for jcritstr assumes a particular strand
         !  composition that does not require a user-defined copper fraction,
         !  so this is irrelevant in this model"

However it then has
         jcritsc = jcritstr / (1.0D0-fcu)

If fcutfsu is a variable and is allowed to 1.0 this will allow the current density jcritsc to reach infinity and push the SC fraction down to zero... if the parameterisation is for a strand, it must impose appropriate values on fcu for the parameterisation.

**Comment by mkovari** [comment]
Bi2212 is a type of BSCCO, a first generation high-temperature superconductor.  Although it is still the only type of HTS available in round wire, no-one seems very interested in it these days.  Issue closed.
