### ISSUE TITLE
Improved CS model, including HTS (high temperature superconductor)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#410]
In GitLab by @mkovari on Sep 21, 2016, 08:45

The model for the Central Solenoid could be made more sophisticated.  This might enable the pulse length to be extended.

* [ ]  There is no good reason to apply an upper limit to the radial thickness `ohcth`.  A thick coil with a small bore should be an option available to the optimiser.  
* [ ]  I don't know how the mutual inductance of the CS coil with the plasma is calculated - it doesn't seem to be in either of the PROCESS papers, or in the "full documentation" files.  We should check that the method used is valid for thick coils.
* [ ]  The self-inductance seems to be incorrect and should be fixed - although this won't have much effect on the results.  Issue #396 
* [ ]  The peak field is described in the PROCESS physics paper.  The data are from M. Wilson, Superconducting Magnets (shelved at 621.318 W2 - see eq. 3.2 and fits to graph 3.3).  Note that the approximations used are only accurate if
outer radius /inner radius < 2, which may not apply. This may need to be fixed.  Also I believe the formulae only apply for homogenous magnets - it may be necessary to include corrections for discrete cables.
* [ ]  There should be an option to divide the coil into two or more concentric sub-coils, with different current densities.  The field is lower on the outside of the coil so the superconductor in this region can have a bigger current density.
* [ ]  Calculations involving the CS seem to generate error messages rather frequently (@jmorris-uk):    

> 74     3   INDUCT: Negative square root imminent; raise ohcth or its upper limit     

* [ ]  As requested by EUROfusion, a High Temperature Superconductor (HTS) option based on REBCO conductor should be included. (See [IDM](https://idm.euro-fusion.org/?uid=2N6XAK))  This will require data from Klaus Weiss at KIT, and should be coordinated with the SYCOMORE team at CEA.  This will have to wait until the HTS TF coil model is finished.

**Comment by ajpearcey** [comment]
Some of these points have been dealt with in other issues and some points can be spun out into separate issues. 

1) We currently have a upper limit of 1m for the CS thickness. We know PROCESS will in some situation find machines with small bore and thick solenoids. 
2) Agreed this poorly documented and this being looked at.
3) I think the mutual induction calculation is incorrect. This is being looked at currently, see here https://github.com/ukaea/PROCESS/discussions/3064
4) See https://github.com/ukaea/PROCESS/issues/1883
5) This is still currently not possible. Is this a high priority request? 
6) See https://github.com/ukaea/PROCESS/issues/423
7) This is done.

I would recommend closing this issue and splitting any remaining tasks into other issues.

**Comment by stuartmuldrew** [comment]
Based on @ajpearcey comments above I will close this issue and split up the remaining tasks into new issues.

**Comment by stuartmuldrew** [comment]
Point 5 is now covered by #3259.
