### ISSUE TITLE
Update Lz data

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#413]
In GitLab by @hlux on Sep 22, 2016, 13:18

Should include Thomas Puetterich's most recent updates for W and add the uncertainties data from Stuart Henderson in. 

Afterwards run another benchmark with ASTRA. (Check what Lz curves they are using!) and understand differences in Q and Xe concentration.

**Comment by ym1906** [comment]
It looks this issue was resolved and merged here: [issue-412-update-loss-data](https://git.ccfe.ac.uk/process/process/compare/develop...issue-412-update-loss-data)

**Comment by mkovari** [comment]
Adam Brown seems to have produced updated impurity radiative loss files from instructions by Martin O'Mullane in his branch.  He deleted a bunch of data files and introduced new ones, labelled 2020-03-31. Can you confirm that his changes were actually implemented in PROCESS?

As far as I know Adam's work was never checked by anyone, so I am not sure what to recommend.
@ym1906

**Comment by ym1906** [comment]
Thanks for the reponse @mkovari.

Actually, it doesn't look like the changes were implemented in PROCESS. @timothy-nunn refreshed this data in 05/23.

In that case, is there a reason to revive this issue?

**Comment by ajpearcey** [comment]
If @timothy-nunn can confirm data was refreshed in 05/23, then i think we can close this issue.

**Comment by ym1906** [comment]
Ok, I will close this issue.
