### ISSUE TITLE
New TBR model from Jon Shimwell

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#416]
In GitLab by @mkovari on Oct 11, 2016, 09:16

Jon has a new set of ~1000 runs for TBR, and a new method of fitting using a "Gaussian process" method, consisting of 1000 Gaussians.  This could be included, either   
(a) wrap the the Python code and calling it from Fortran,   
(b) writing Fortran code to evaluate the Gaussians, or  
(c) wait until PROCESS is fully or partly refactored.  

However...as far as I know the blanket thickness, major and minor radii etc are all fixed, which may make the model unsuitable.

**Comment by mkovari** [comment]
As mentioned above, the model from Jon (even if it were still available) is not suitable.  I have emailed Chantal Shand to see if her team might come up with a surrogate model for TBR.  For the time being I will close this issue. 
@jonmaddock
