### ISSUE TITLE
ralpne overwrites fimp(02) in IN.DAT

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#417]
In GitLab by @hlux on Oct 14, 2016, 13:52

The thermal helium fraction is set via ralpne, but all ion species are also stored in fimp(). Therefore ralpne should always be equal to fimp(02). However, both can be set separately in IN.DAT and ralpne always overwrites fimp(02). 

Ideally conflicting values should be flagged up in any PROCESS run, but definitely in the GUI changing one should also change the other!

**Comment by ym1906** [comment]
As we no longer have a GUI for PROCESS, there is no longer confusion in this regard with setting conflicting values.

The behaviour is still the same, `ralpne` overwrites the `fimp(02)`. A simple solution is to simply remove `fimp(02)` from any template input files in favour of `ralpne`. I think a review of the impurity radiation data structure is due, but this is a larger piece of work.

**Comment by jonmaddock** [comment]
Should this really be closed? GUI or not, the issue is still there. I don't think this is about reviewing the impurity radiation data structure, I think it's about preventing one input from overwriting the other. Should either , `ralpne` or `fimp(02)` be removed?

**Comment by ym1906** [comment]
This value is controlled by `ralpne` , in fact changing fimp(2) does not change the value of the parameter. It also doesn't make sense that a user would set these two parameters to different values in the first place.

However, as fimp(2) is part of the fimp array, it's not straight forward to remove it as an input variable. All members of fimp(1:13) are inputs, and all of them are output (and still used by other parts of the code).  A generic fortran function loop for looping through arrays is used to set them as inputs. It doesn't seem elegant to add a specific exception to this function.

I have added a warning to the user when they change fimp(2) from the default value, and they are told to use ralpne instead.
