### ISSUE TITLE
Parabolic profiles going to zero at rho=1 & Te at edge

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#448]
In GitLab by @jmorris-uk on Nov 21, 2016, 16:30

Discuss parabolic profiles going to zero at `rho=1` for `ipedestal=0`.

Possible introduce a constant in the equation to provide non-zero values at rho=1?

@mkovari @hlux @rkemp @jcrivas

**Comment by mkovari** [comment]
To cut a long story short, having zero values of temperature and density at the edge in L-mode profiles is not physically realistic, but not a problem for us at the moment.
