### ISSUE TITLE
Revisions to versions including Kallenbach divertor model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#476]
In GitLab by @mkovari on Feb 20, 2017, 13:22

1.  The output line from the radiation model, `Radiation Power :` should be revised to read `Radiation Power  (excluding SOL)`.   

2.  The following is an output if `iscdens =1`, and should then show OP.
```
Electron density pedestal height (/m3)                                   (neped)                   6.282E+19     
```

3.  Combine `kallenbach_plotting.py` into `plot_proc`.  Run the code only when `kallenbach_switch=1`.

**Comment by timothy-nunn** [comment]
Point 1 implemented already. `iscdens` switch does not appear to exist anymore, so point 2 no longer required. Kallenbach model removed so point 3 invalid.
