### ISSUE TITLE
Split off and remove old divertor model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#499]
In GitLab by @mkovari on Apr 6, 2017, 14:17

The old divertor model is obsoplete, but there are several important variables listed in `module divertor_variables` in global_variables.f90 which we still need in the machine build, such as `rspi` and `rspo`.  They should be put into a different variable module.  The old divertor module should then be removed.

I have moved the following into build_variables:
plsepi, plsepo, plleni, plleno, rspo.

**Comment by chris-ashe** [comment]
@jonmaddock 
Is this issue now obsolete as the Kallenbach model has been removed?

**Comment by chris-ashe** [comment]
Having looked at the code the issue with removing the old divertor model is no longer needed as this was addressed in the open-sourcing and the Pythonisation of the module.
