### ISSUE TITLE
Internal code overwrite of input parameters

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#510]
In GitLab by @rkemp on May 3, 2017, 13:13

There are a number of places where the code overwrites global input variables without comment. I think this is very bad practice and can lead to situations where the user thinks they have set a parameter, but in reality no change is made. In particular I think this is common in the blanket modules (a recent offender was *fdiv* being forced to a value of 0.115).

While some models clearly need to be kept within bounds, my suggestion is that in any cases where there is such a forced value in a model, it is reported in the OUT.DAT and to the console: something like "CCFE HCPB blanket model requires fdiv = 0.115". Hopefully this will aid troubleshooting and avoid frustration when the code seems unresponsive to changes.

@mkovari @jmorris-uk @mkumar any comments or suggestions?

**Comment by timothy-nunn** [comment]
`fdiv` being manually set removed 2018-11-07

**Comment by timothy-nunn** [comment]
The list of constants being set in Python files:

[setting_constants.txt](https://github.com/ukaea/PROCESS/files/14664900/setting_constants.txt)

**Comment by timothy-nunn** [comment]
@ym1906 @ajpearcey can you comment on https://github.com/ukaea/PROCESS/blob/main/process/plasma_profiles.py#L62-L68 it appears this bit of the code could reset variables that are inputs without a warning?

**Comment by ajpearcey** [comment]
the parabolic_parameterisation is only for an L-mode plasma, so these variables are being forced to be correct values for an L-mode profiles.

I imagine you could have an warning when calling parabolic_parameterisation if your in.dat used inputs that describe a H-mode plasma (ipedestal != 0).

**Comment by timothy-nunn** [comment]
@geograham should having ipump be necessary if this check is going to overwrite the input value? Should we just warn the user if they need to check their `ipump`?
