### ISSUE TITLE
Change iteration variables to prevent negative winding pack thickness

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#515]
In GitLab by @mkovari on May 10, 2017, 15:48

Please note: we should all be using `thkcas` and `thkwp ` as iteration variables! @hlux @kellis @jmorris-uk @stuartmuldrew @mkumar 
---------------------------------------------

At the moment we somtimes get negative winding pack thickness.
This is because the total TF coil thickness `tfcth`  and the TF nose thickness `thkcas`  are both iteration variables.  The winding pack thickness results from subtracting them:
```
thkwp = tfcth - casthi - thkcas - 2.0D0*tinstf - 2.0d0*tfinsgap
```
There is nothing to stop this going negative.

The simplest approach is to swap so that `thkcas` and `thkwp ` are iteration variables.  Then they will add rather than subtract when calculating the total thickness `tfcth`.  (We would probably add a line in `initial.f90` to ensure that `tfcth` is defined correctly at the start.)

(It *may* be possible instead to create a new constraint to ensure that  `tfcth` is always bigger than `thkcas`, but if the constraint residual is not calculated until *after* the code crashes then there is not much point.)

I have made it backwards compatible, with a new iteration variable 140.  The following code appears in machine_build.f90:
```
    ! Calculate tfcth if thkwp is an iteration variable (140)
    if (any(ixc(1:nvar) == 140) ) then
        tfcth = thkwp + casthi + thkcas + 2.0D0*tinstf + 2.0d0*tfinsgap    
    endif
```
and this in sctfcoil.f90:
```
    if (any(ixc(1:nvar) == 140) ) then
        tfcth = thkwp + casthi + thkcas + 2.0D0*tinstf + 2.0d0*tfinsgap
    else
        thkwp = tfcth - casthi - thkcas - 2.0D0*tinstf - 2.0d0*tfinsgap
    endif
```

**Comment by mkovari** [comment]
See discussion #2923.
