### ISSUE TITLE
RuntimeError when calling interpolate in math_library.f90

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#566]
In GitLab by @hlux on Sep 29, 2017, 11:33

When running the most recent version of process with the attached input file [IN.DAT](https://git.ccfe.ac.uk/process/process/uploads/a76bab664d2fed40c055b64f89e9cbe4/IN.DAT) I get the following Runtime Error:
```
At line 570 of file maths_library.f90
Fortran runtime error: Index '0' of dimension 1 of array 'x_array' below lower bound of 1
```

This is in function interpolate which is called from read_and_get_atomic_data.f90 and read_radiation.f90.

**Comment by clmould** [comment]
The interpolate function is no longer used and this input file uses the Kallenbach model so we can't recreate the error, but will remove the interpolate function from maths_library.f90
