### ISSUE TITLE
Improve clarity of beta limit options

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#567]
In GitLab by @mkovari on Oct 4, 2017, 13:22

The options for how to set the g-value in the beta limit are a little opaque.  (Note that this is distinct from the question of which value of beta to constrain, which is set by `iculbl`.)  The following might be useful: 

1. Reduce the two switches (`iprofile` and `gtscale`) to one switch with three or more options.  
2. Explain the option used more clearly in the OUT.DAT.

Here are the switches and relevant variable:
```
iprofile /1/ : switch for current profile consistency:
    = 0 use input values for alphaj, rli, dnbeta (but see gtscale option);
    = 1 make these consistent with input q, q0 values (recommendation: use icurr=4 with this option) 

dnbeta /3.5/ : (Troyon-like) coefficient for beta scaling; calculated as (4.0*rli) if iprofile=1 (see also gtscale option) 

gtscale /0/ : switch for a/R scaling of dnbeta (iprofile=0 only):
    = 0 do not scale dnbeta with eps;
    = 1 scale dnbeta with eps
```
Note that the term "beta scaling" used above is not very helpful.

The three options listed in the Physics paper might be the way to implement this:  
![image](https://github.com/ukaea/PROCESS/assets/9718416/80201550-aea7-45ff-a3d4-300b7074bb97)

A reference would also be useful, as there isn't one in the physics paper!  
(If $`l_i`$ is used it would help to explain how it is derived.)

EDIT 15/5/24
I have found the reference for $g=4 l_i$: equation 18.57 on page 584 of Fusion Plasma Physics, Stacey, 2nd ed.

**Comment by stuartmuldrew** [comment]
I have removed ```gtscale``` and added the functionality to ```iprofile```.
