### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#572]
In GitLab by @mkovari on Oct 18, 2017, 14:14

* [x]  Rename `theat` , as heating is required throughout the pulse. eg `t_fusion_ramp`  
* [x]  Vacuum pumping and pre-charge are in parallel.  
* [ ]  Redefine the term 'dwell time': any time outside plasma current flat-top.  (TBC: why not any time outside fusion power flat-top?)
* [ ]  Put in a place-holder for the delay in between ramp-down and pre-charge (currently called `tdwell`), e.g. `t_delay`. Set it to zero.   
* [ ]  Remove the old timings image from the html output.  
* [ ]  Replace with an updated image when this is ready.

@fmavig @jmorris-uk @hlux   
This is from a discussion between Michael and Francesco.

**Comment by j-a-foster** [comment]
Checked that a switch exists for having the vacuum pumping and pre-charge in parallel or not.
