### ISSUE TITLE
Calculation of Tresca stress in TF winding pack

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#580]
In GitLab by @mkovari on Nov 9, 2017, 08:45

Section 2.4.3 of the PROCESS engineering paper explains that 
>Because the structural material inside the winding pack is assumed to take the form of radial and tangential webs (Fig. 7), the limiting von Mises stress in this zone is given by the larger of the two values:  
![image](https://git.ccfe.ac.uk/process/process/uploads/9785d7c2ede038a3fbfd91a00fb9bda8/image.png)

I think we should adopt the same method when calculating the two Tresca stresses: 
1. Calculate the radial stress in the radial webs, and combine with the vertical stress;
2. Calculate the tangential stress in the tangential webs, and combine with the vertical stress.

We need to think about how these are derived from the single set of smeared stresses.

**Comment by ajpearcey** [comment]
look at this line 

 # Array equation
        sig_tf_tresca_tmp1 = numpy.maximum(
            numpy.absolute(sig_tf_r - sig_tf_t), numpy.absolute(sig_tf_r - sig_tf_z)
