### ISSUE TITLE
plot_proc.py very DEMO centred

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#631]
In GitLab by @hlux on Mar 16, 2018, 11:16

As we are extending our portfolio to very different machines, could we also make the plot_proc.py tool a bit more variable to nicely display other machine designs? 

For example this ORNL output does not come up very nicely. And a lot of variables are missing. 

[SUMMARY.pdf](https://git.ccfe.ac.uk/process/process/uploads/f889695e33100eaa1015f4a0a70685c5/SUMMARY.pdf)

[MFILE.DAT](https://git.ccfe.ac.uk/process/process/uploads/d8e2418819172b8c8fecdd4e026ecb95/MFILE.DAT)

**Comment by kj5248** [comment]
For the most part seems to already be done. Axis is adaptable, although not done to nearest 5m but this is likely not needed.

```
if demo_ranges:
   axis.set_ylim([-15, 15])
   axis.set_xlim([0, 20])

# Adapatative ranges
else:
   axis.set_xlim([0, axis.get_xlim()[1]])
```

Additionally I checked and ST and double null both work fine.
