### ISSUE TITLE
fvsbrnni vs. mhd%f_ni

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#646]
In GitLab by @hlux on Mar 23, 2018, 11:13

Dear @efable ,

I am sure you have explained this in the past and I just can't find your e-mail right away. fvsbrnni is our PROCESS iteration variable for the fraction of the plasma current produced by non-inductive means. This is an input to PLASMOD via inp0%f_ni. How does PLASMOD handle this internally again and why can there be a different value in mhd%f_ni? Or should mhd%f_ni always be equal to fvsbrnni??

Thanks,

Hanni

@kellis for reference.

**Comment by mkovari** [comment]
This relates only to Plasmod and can be closed.
