### ISSUE TITLE
Hstar calculation incorrect?

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#652]
In GitLab by @hlux on Apr 4, 2018, 10:45

Dear @jmorris-uk ,

I have just looked at our calculation for Hstar (non-radiation corrected H-factor) in plot_proc.py and I believe it is wrong. In our radiation correction we calculate P_loss = P_heat - P_core. (if iradloss = 1)

The current implementation reads 

>>>
    hstar = hfact * (powerht / (powerht + psync + pbrem)) ** 0.31
>>>

I think this is only valid for our old radiation model, where pcore = psync + pbrem.
but I think it probably should be (if iradloss = 1)

>>>
    hstar = hfact * (powerht / (powerht + pcore)) ** 0.31
>>>

or if iradloss = 0

>>>
    hstar = hfact * (powerht / (powerht + prad)) ** 0.31
>>>

@rkemp Do you have any further comments?

Would you mind implementing that correction in plot_proc.py and checking whether this makes a significant difference for e.g. our baseline runs?

Thanks,

Hanni

**Comment by jmorris-uk** [comment]
The radiation correction should be implemented in a consistent way inside of process itself and should be inside the confinement time options. Review of the confinement time scalings should take place and amended. Discussion moved to here https://github.com/ukaea/PROCESS/discussions/3138.
