### ISSUE TITLE
Copper TF Coil Heating and Pulse Length

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#655]
In GitLab by @stuartmuldrew on Apr 9, 2018, 13:57

TF heating is not used in the pulse length calculation, and equally the pulse length is not considered in the TF heating.

The average inboard leg temperature can be set as an input, tcpav (=100C default).  This is used to calculate the resistivity of the inboard leg (rhocp = 1.0D-8 * (1.72D0 + 0.0039D0*tcpav) / 0.92D0), and this is then used to calculate the resistive power, prescp.  An upper limit on the resistive power for the whole TF coil can be set by activating constraint equation 19 with the limit, mvalim (=40.0MW default), and f-value, fmva (=1.0 default).  The coolant fraction, fcoolcp (=0.3 default), is used in the area and volume calculations only.

We could consider incorporating parts of the ST centrepost cooling model into the TF coil inboard leg and then use the heating in determining the pulse length.

**Comment by ym1906** [comment]
@mkovari @stuartmuldrew 

Do you have any comment on whether this issue should be revived?

**Comment by stuartmuldrew** [comment]
I think this issue should be closed, as the feature suggested isn't needed.
