### ISSUE TITLE
Replacing sys.exit in python tools

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#658]
In GitLab by @hlux on Apr 12, 2018, 11:34

Matti has raised an issue with the sys.exit statements in our systems code. He suggested replacing them on the following grounds (email to J. Shimwell on same topic):

>>>
sys.exit() considered harmful:
Ok to be honest, I don't really know what people think of this, but when running in an IDE at least, this throws less clear error messages:

print('material_card_name must be provided when making a serpent_material_card from a material')
sys.exit()

gives:

Material()
A list of elements present within the material must be specified
An exception has occurred, use %tb to see the full traceback.

SystemExit

/home/mc2056/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

Basically the first thing you see is SystemExit in bright red :D
whereas,

    raise ValueError('A list of elements present within the material '
                               'must be specified')

Material()

Traceback (most recent call last):

  File "<ipython-input-61-c9a6cf1dec32>", line 1, in <module>
    Material()

  File "/home/mc2056/Code/neutronics_material_maker/neutronics_material_maker/nmm.py", line 1478, in __init__
    raise ValueError('A list of elements present within the material '

ValueError: A list of elements present within the material must be specified

The latter gives me an Error which relates to the problem, and a code line_number (without having to type %tb in the console). The former ok I guess if you are working from the command line, but in some IDEs / consoles, sys.exit() will actually close the console (at least in my experience).
>>>

Hence, we could consider a different approach to sys.exit in python.  @jmorris-uk, @mkovari and @mkumar any comments?

I always thought appropriate error treatment is to catch all errors and if necessary cleanly exit with sys.exit. However, following Matti's argument this seems to be extremely unhelpful when running with his IDE.

**Comment by clmould** [comment]
This isn't a problem any more
