### ISSUE TITLE
treatment of f_ni and Psep in PLASMOD vs PROCESS

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#659]
In GitLab by @efable on Apr 12, 2018, 13:02

@hlux @kellis 

Presently, fvsrbnni and fvalue for psepbqarmax are possible iteration variables. However, that dont work in PLASMOD. 
For the moment, we use fvsrbnni and psepbqarmax as inputs, without iteration associated, and also without Psep constraint.

To put back fvsrbnni and fvalue for psepbqarmax as possible iteration variables (which make sense on the long term), we have to think at how PLASMOD can use this without creating bifurcations which VMCON would not like (if Psep constraint is set up again).

For the fraction of n.i. current, most logical values are 0 or 1, without iteration variable, however, the iteration variable would make sense for intermediate scenarios with longer pulses (but not fully n.i.). At the moment, the solution to this has to be thought.

For Psep, again, psepbqarmax with fvalue cannot be used in iterations, however that would make sense when Kallenbach is used, because the non-linearities associated with Psep, SOL, and plasma behavior would lead to some room for omptimization with psepbqarmax*fvalue as iteration variables. But also this one has to be thought through before using it as iteration variable.

**Comment by mkovari** [comment]
This lengthy discussion relates to Plasmod and can be closed.
