### ISSUE TITLE
No documentation of create_xls.py

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#671]
In GitLab by @hlux on Apr 24, 2018, 14:42

@mkovari could you please write a documentation for the create_xls.py utility in the PROCESS user guide. 

Thanks,

Hanni

**Comment by jmorris-uk** [comment]
`create_xls.py` no longer exists within the repo and `mfile_to_csv.py` is still present. If more functionality is to be added then it can be done there.
