### ISSUE TITLE
Update cad_output.py for new TF coil shape

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#677]
In GitLab by @jmorris-uk on Apr 30, 2018, 10:35

Since change in TF coil shape [cad_output.py](utilities/cad_output.py) no longer correctly plots the TF coils.

[mcnp_output.py](utilities/mcnp_output.py) also needs updating.

**Comment by ajpearcey** [comment]
Both the utilities cad_output.py and mcnp_output.py have been removed from the code several years ago. This issue is no longer relevant and will be closed
