### ISSUE TITLE
1D relevant NBI model from ASTRA

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#685]
In GitLab by @kellis on May 3, 2018, 13:50

From Hanni's list of action items (meeting 02/05/2018)

3) EF: Implement 1D relevant NBI model from ASTRA with more realistic current drive profiles; 

Then...KE/HL: Assure the technology coupling is done correctly within PROCESS

@hlux

**Comment by stuartmuldrew** [comment]
I recommend closing this issue.

The DEMO baseline no longer uses NBI making this not a priority.  It is also unclear, now PROCESS is open source, what the IP situation is with using ASTRA models.
