### ISSUE TITLE
Improve the interpolation method for the core and edge plasma

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#689]
In GitLab by @kellis on May 3, 2018, 14:00

Action item from meeting 02/05/2018

7) EF: Consider improving the interpolation method for the core and edge plasma. (Not super urgent, as the volume in those regions is small and therefore the effect is expected to be small, but currently the profiles look unrealistic with a dip in the electron temperature at the core and negative bootstrap currents in ASTRA which also cause an issue for the equilibrium solver.)

**Comment by mkovari** [comment]
I believe this relates only to PLASMOD.
