### ISSUE TITLE
Make current profiles and the safety factor profiles consistent in PLASMOD

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#691]
In GitLab by @kellis on May 3, 2018, 14:07

Action item from meeting 02/05/2018

9) EF: You mentioned that currently the current profiles and the safety factor profiles in PLASMOD are not yet consistent (with respect to their sawtooth treatment?) You planned to make them more consistent.

**Comment by j-a-foster** [comment]
Closing as PLASMOD has been removed from PROCESS.
