### ISSUE TITLE
Protium output is zero in PROCESS-PLASMOD

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#703]
In GitLab by @kellis on May 16, 2018, 11:47

The output dnprot is currently zero when running with PLASMOD, but non-zero with 0D.

In plasmod.f90 we set dnprot to (protium*dene). This is only non-zero when protium is set to a value by the user - default is zero as typically there is no proton seeding. 

In physics.f90 an estimate is made for protons produced by DD reactions, although this seems quite basic

    if (alpharate < 1.0D-6) then  !  not calculated yet...
       dnprot = max(protium*dene, dnalp * (fhe3 + 1.0D-3)) !  rough estimate
    else
       dnprot = max(protium*dene, dnalp * protonrate/alpharate)
    end if

@efable Will the proton composition be output from PLASMOD? Perhaps this value is not important at this stage.

@hlux

**Comment by mkovari** [comment]
This relates only to Plasmod, which has been removed.
