### ISSUE TITLE
A few NBI beam properties not being calculated

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#704]
In GitLab by @kellis on May 16, 2018, 14:35

@hlux @efable Not sure how important this is, but noting now to remember for a later date. These values may also contribute to other outputs.

The following beam results are currently zero in PROCESS/PLASMOD OUT.DAT, even though NBI is being used:

betanb, beam ion beta
palpnb, beam-plasma alpha power

**Comment by mkovari** [comment]
This issue relates only to Plasmod which has been removed, so I will close it.
