### ISSUE TITLE
PF power supplies accounting

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#714]
In GitLab by @rkemp on May 23, 2018, 09:43

I have added a new contribution to the electrical energy required for the CS and PF coils.

Electrical energy is dissipated in PFC power supplies *only* when they increase or decrease the poloidal field energy.  This assumes that the power supplies include an energy storage system and that currents in the coils can be varied without loss when there is no change in the energy in the poloidal field. Energy is dissipated only when energy moves into or out of the store in the power supply.

(The poloidal field energy is the energy stored in the poloidal magnetic field, due to the plasma, the CS, and the PF coils.  Their separate contributions cannot be distinguished, as the energy density is not linear in the field.  It is possible, however, to distinguish the energy in the poloidal field from that in the toroidal field which is orthogonal.
```
  !+ad_vars  etapsu /0.9/ : Efficiency of transfer of PF stored energy into or out of storage.
  real(kind(1.0D0)) :: etapsu = 0.9D0
```

```
    do time = 1,5
        ...
        ! Electrical energy dissipated in PFC power supplies as they increase or decrease the poloidal field energy
        ! This assumes that the energy storage in the PFC power supply is lossless and that currents
        ! in the coils can be varied without loss when there is no change in the energy in the poloidal field.
        ! Energy is dissipated only when energy moves into or out of the store in the power supply.
        ! Issue #713
        pfdissipation(time) = abs( poloidalenergy(time+1)-poloidalenergy(time) ) * (1 /etapsu - 1)
    end do
    ! Mean power dissipated
    ! The flat top duration is the denominator, as this is the time when electricity is generated.
    pfpower = sum(pfdissipation(:)) / (time(5) - time(4))
    pfpowermw = pfpower / 1.d6
    ...
    !  PF wall plug power dissipated in power supply for ohmic heating (MW)
    !  This is additional to that required for moving stored energy around
    wall_plug_ohmicmw  = pohmmw * (1 /etapsu - 1) 
    ! Total mean wall plug power dissipated in PFC and CS power supplies.  Issue #713
    pfwpmw = wall_plug_ohmicmw + pfpowermw

    ! Waste heat generated in PFC and CS power supplies (MW),
    ! classed as "secondary waste heat"
    pfsec = pfwpmw
```

For simplicity I have left the output description unchanged:
```
Electric power for PF coils (MW)                                         (pfwpmw)                      1.061  OP 
```
The value of this power loss has increased from about 0.15 MW to 1 MW.

---------------------------------------------
*Original issue*

There seems to be a significant error in accounting for the power fed to the PF coils. There is a variable 
```
!+ad_vars  etapsu /0.9/ : Efficiency of ohmic heating
```     
which is then used as follows:
```
    !  PF Power requirements
    !  Wall plug power (MW)
    pfwp = pohmmw / etapsu
```
This in turn is used for the power balance:
```
    !  Electrical power consumed by fusion power core systems
    !  (excluding heat transport pumps and auxiliary injection power system)
    !  Added pfwp (waste heat from PF coil ohmic heating)
    pcoresystems = crypmw + fachtmw + ppumpmw + tfacpd + trithtmw + vachtmw + pfwp
```
This is not correct.  The ohmic power `pohmmw` is always small, and is actually zero for non-inductive machines.

To see the magnitude of this apparent error, in the 2018 baseline, ramp-up of the PF system (including the plasma and CS) requires 59 MW of power to be fed in, while during the ramp-down 212 MW must be extracted, and dissipated or stored.  I don't think these large power flows are taken into account.

![image](https://git.ccfe.ac.uk/process/process/uploads/3ba9fa806ac2e24e78c1fc87166abf90/image.png)

--------------------------
Note Richard's original comment:  
In the 2017 baseline I see under the section "Electric Power Requirements"  
>  PF coil power supplies (MW)                                              (ppfmw)                   1.160E+02  OP  

and then  

>  Total pulsed power (MW)                                                  (pacpmw)                  6.031E+02  OP

which is the sum of the powers in that section. However, under the plant electrical power balance this PF power is missing. Under the 'intermittent power usage' table the PF power during burn is indeed very low, but none of the numbers in this table match the 116 MW from ppfmw. What does this number actually represent and why is the total pulsed power inconsistent with the power consumption during a pulse?

**Comment by jmorris-uk** [comment]
# Papercut review 2024

The content of this issue was merged into `develop` on the old GitLab repo back in July 2019 `6a9b4e89` and therefore should be closed.

#972 is an extension of this issue with a discussion to replace the existing calculations with something new. Further work on this should be carried out there.
