### ISSUE TITLE
Tidy up and document PLASMOD outputs

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#727]
In GitLab by @kellis on Jun 21, 2018, 11:36

For further down the road...

We have PLASMOD outputs in various formats, coming from both PLASMOD directly and PROCESS. Can we consolidate these a bit, or are they all still needed for diagnostics at this stage?

For the output files we want to keep permanently, can we document the contents and rename them in English.

@efable @hlux

**Comment by athoynilimanew** [comment]
I conducted a search and found no .out file similar/connected to PLASMOD or no mention of PLASMOD anywhere.

I believe this issue is out of date and it is safe to close.
