### ISSUE TITLE
Fusion power volume integration

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#766]
In GitLab by @mkovari on Oct 1, 2018, 11:30

The calculation of fusion power uses this formula:
```
       !  Fusion reaction rate (m3/s) is calculated in fint for each ireaction
       !  sigmav is the volume-averaged fusion reaction rate (m3/s)
       !  = integral(2 rho sigv(rho).ni(rho)^2 drho) / (deni**2)
```
The volume element is included in the 2*rho factor: $`dV=2\pi r dr`$

This seems a bit crude as it applies only for circular flux surfaces.  It is true that in the core where the fusion takes place the local elongation and triangularity are small.  Would it be practical to use a more accurate formula taking account of elongation of the flux surface?

**Comment by mkovari** [comment]
In all JETTO runs, dV/drho is output in the signal profiles / DVEQ.
