### ISSUE TITLE
Change iteration variables to prevent negative dimension of space inside cable (m)

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#785]
In GitLab by @mkovari on Dec 4, 2018, 15:29

Previously I adjusted the TF code to prevent negative winding pack thickness (#514).  We also often get errors due to negative values of `leni` (the width of the space inside the cable).  This is because `leni` is derived by subtraction:
```
leni = conductor_width - 2.0D0*thwcndut
```

It would be nice to eliminate this problem by building the winding pack up from the inside to avoid subtractions.

@jmorris-uk @ajpearcey @stuartmuldrew @hlux

**Comment by mkovari** [comment]
See discussion #2923.
