### ISSUE TITLE
run_process.py completely changes values in IN.DAT file

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#791]
In GitLab by @hlux on Jan 22, 2019, 11:16

[run_process.conf](https://git.ccfe.ac.uk/process/process/uploads/e2a76ce15bcfee56884de5c125dd629d/run_process.conf)[IN.DAT](https://git.ccfe.ac.uk/process/process/uploads/7cdab02da5a1aab41a944220972ee2a5/IN.DAT)[OUT.DAT](https://git.ccfe.ac.uk/process/process/uploads/688044e4f9316108e247921f51965f48/OUT.DAT)[IN.DAT](https://git.ccfe.ac.uk/process/process/uploads/054a7730c7f7a016447246e1936ad85e/IN.DAT)[OUT.DAT](https://git.ccfe.ac.uk/process/process/uploads/924b772919ebe1ce3c125e9a47e4c548/OUT.DAT)

**Comment by kj5248** [comment]
Ran a VaryRun using run_process.conf (the replacement to run_process.py) and the created .DAT files all came out without this problem so will close this issue.
