### ISSUE TITLE
Remote Maintenance Constraints

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#862]
In GitLab by @jmorris-uk on Jun 14, 2019, 09:34

After DEMO configuration meeting and discussions with Oliver Crofts and Tony Loving, will look into best way forward for including remote maintenance considerations in PROCESS.

Mainly will involve:
*  Geometry and space allocation
*  Blanket segmentation and masses
*  Maintenance time
*  Costs (maybe)
*  Building sizes

**Comment by ajpearcey** [comment]
I have move this to a discussion here https://github.com/ukaea/PROCESS/discussions/3288

for now I will close this issue.
