### ISSUE TITLE
Separate constraint tolerance from VMCON tolerance.  mdkdevelop3

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#871]
In GitLab by @mkovari on Jun 21, 2019, 21:03

I created a branch mdkdevelop3 with some useful code, but the branch is now too old to make it practical to merge.  It will be easier to recode by hand if and when we choose to do so.

To see what there is, do a compare (or just visit this [link](https://git.ccfe.ac.uk/process/process/compare/develop...mdkdevelop3)).

1. Allow the constraint tolerance to be different from the optimiser tolerance.  
2. New verbose diagnostics.

**Comment by timothy-nunn** [comment]
It is my opinion that this is no longer really necessary. #3238 ensures that the inequality constraints are satisfied, no exceptions. Do we still want to introduce a separate equality tolerance to PROCESS?

@jonmaddock @mkovari

**Comment by mkovari** [comment]
To clarify the situation: the code as it stands ensures that the inequality constraints are satisfied, but it no longer has a separate explicit check on the equality constraints.  They should be guaranteed by the convergence criterion which also ensures the optimiser has converged.  I agree that there is probably no need for an additional check on the equalities.

I suggest keeping an eye on the constraint residues to check that they remain low.
