### ISSUE TITLE
Minor bug in plasma volume

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#880]
In GitLab by @mkovari on Jul 10, 2019, 13:37

Plasmod overwrites the plasma volume calculated by PROCESS.
  
In Plasmod the volume is calculated by numerical integration using subroutine INITEQUIL:
```
V = cumint1(dvdr * gradient1(rhoint))
````
which is later copied into mhd%vp:
```
mhd%Vp = V(nx)
```
and then into vol, overwriting its previous value:
```
vol = mhd%vp ! plasma volume (m^3)
```
(subroutine convert_Plasmod2PROCESS).  
This results in two different values of the plasma volume, which never converge to a single value:
```
 PLASMOD:           Plasma volume     2448.5162990830318     
 Subroutine geomty: Plasma volume     2465.5702962059686     
 PLASMOD:           Plasma volume     2448.5163137893992     
 Subroutine geomty: Plasma volume     2465.5702962059686     
 PLASMOD:           Plasma volume     2448.5163133818191     
 Subroutine geomty: Plasma volume     2465.5702962059686     
 PLASMOD:           Plasma volume     2448.5163133810902     
 Subroutine geomty: Plasma volume     2465.5702962059686     
 PLASMOD:           Plasma volume     2448.5163133810611     
 =>    8  vmcon iterations. Normalised FoM =  0.7987  Residuals (sqsumsq) = 3.9E-06  Convergence param = 5.6E-07
 
 ************************************* PROCESS found a feasible solution **************************************
```

Anything calculated from the volume will also have two possible values.  It is also just possible that this is interfering with convergence in some circumstances.

I suppose we should decide which is more accurate and remove the other calculation.  The formula we keep should be
* [ ]  Compatible with both single and double null options (preferably giving different results for the two cases)
* [ ]  Compatible with small aspect ratio tokamaks 
* [ ]  Compatible with input files that do not use Plasmod.

I propose to remove the line in Plasmod that overwrites the `vol` variable in PROCESS.  Comments @efable @stuartmuldrew  ?

## Steps to reproduce
Any input file using Plasmod.  
Uncomment the three write statements whose outputs are shown above.

## Checklist

After fixing bug do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, explain.
* [ ] Does it change the baseline 2019 run? If so, explain.
* [ ] Merge request created

**Comment by mkovari** [comment]
Plasmod has now been removed so this issue is obsolete.
