### ISSUE TITLE
Discrepancy in H factor

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#881]
In GitLab by @mkovari on Jul 11, 2019, 14:57

According to the 2019 baseline Plasmod output (K:\Power Plant Physics and Technology\PROCESS\DEMO Baseline Runs\2019\) the H-factor is only **0.892**:  
```
Computed H factor according to ITER 98 y2 elmy H mode     (loss%H)            0.892
```
and this is repeated in the main part of the output:
```
Confinement scaling law      IPB98(y,2)           (H)
Confinement H factor                                      (hfact)             0.892
```
However, this value is obviously too small, and it contradicts the table of H-factors:
```
 ***************************** Energy confinement times, and required H-factors : *****
 
    scaling law              confinement time (s)     H-factor for
                                 for H = 1           power balance
 
 IPB98(y,2)           (H)          5.440                   1.192
```

## Checklist
* [ ] Create branch named issue-880
* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run?
* [ ] Commit, push, create merge request

**Comment by j-a-foster** [comment]
@mkovari was this a PLASMOD-specific problem or a wider H-factor calculation problem?

**Comment by mkovari** [comment]
It was purely a Plasmod problem.
