### ISSUE TITLE
Plasmod temperature profiles

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#882]
In GitLab by @mkovari on Jul 12, 2019, 11:07

Plasmod is still generating temperature profiles that have a dip in the plasma centre, with non-zero slope at the centre.  The dip is physically implausible, and the non-zero slope means that the temperature is not even a smooth function, which is impossible.
![image](https://git.ccfe.ac.uk/process/process/uploads/2277f5e9deaeea1c95e4b46c2bf251f1/image.png)

([DEMO 2019 Baseline](https://idm.euro-fusion.org/?uid=2NT5PD))

Any advice @efable, @msiccini  ?

**Comment by ym1906** [comment]
We are no longer using PLASMOD, therefore this issue can be closed!
