### ISSUE TITLE
MFILE format consistency

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#888]
In GitLab by @emiralle on Jul 17, 2019, 23:22

I'm currently coupling COSSAN and PROCESS to perform UQ analyses with this software. COSSAN can be applied to 3rd party solvers (e.g, PROCESS).
The way it works is by treating this 3rd party solver as a black-box. COSSAN writes an input file (IN.DAT) and reads an output file (MFILE.DAT).
The MATLAB class in charge of reading the solver output is called Extractor and there are a few ways to define how are we going to read the data. The simplest way is by associating the output of a variable to a specific number of row and column. There are other methods, but all of them suffer of the problem I'm going to explain next.

PROCESS (as far as I'm concerned) has three different MFILE formats. For example, when ifail=1 the MFILE looks like this:

```
 # PROCESS #
 # Power Reactor Optimisation Code #
 # PROCESS #
 # Power Reactor Optimisation Code #
 PROCESS_version_number__________________________________________________ (procver)_____________________     "1.0.13   "
 Date_of_run_____________________________________________________________ (date)________________________     "15/07/2019"
 Time_of_run_____________________________________________________________ (time)________________________     "23:13"
 User____________________________________________________________________ (username)____________________     "enmidol" 
 PROCESS_run_title_______________________________________________________ (runtitle)____________________     "Run Title (change this line using input variable 'runtitle')                                       
 PROCESS_tag_number______________________________________________________ (tagno)_______________________     "1.0.13-499-g78dfc55"                                                                               
 PROCESS_last_commit_message_____________________________________________ (commsg)______________________     "Reformat lines for inclusion in .bashrc as code.,"                                                 
 # Numerics #
 VMCON_error_flag________________________________________________________ (ifail)_______________________              1    
```
But when ifail=6 we have this:

```
 # PROCESS #
 # Power Reactor Optimisation Code #
 # PROCESS #
 # Power Reactor Optimisation Code #
 PROCESS_version_number__________________________________________________ (procver)_____________________     "1.0.13   "
 Date_of_run_____________________________________________________________ (date)________________________     "15/07/2019"
 Time_of_run_____________________________________________________________ (time)________________________     "23:13"
 User____________________________________________________________________ (username)____________________     "enmidol" 
 PROCESS_run_title_______________________________________________________ (runtitle)____________________     "Run Title (change this line using input variable 'runtitle')                                       
 PROCESS_tag_number______________________________________________________ (tagno)_______________________     "1.0.13-499-g78dfc55"                                                                               
 PROCESS_last_commit_message_____________________________________________ (commsg)______________________     "Reformat lines for inclusion in .bashrc as code.,"                                                 
 # Numerics #
 # PROCESS COULD NOT FIND A FEASIBLE SOLUTION #
 # PROCESS COULD NOT FIND A FEASIBLE SOLUTION #
 VMCON_error_flag_(ifail)________________________________________________ ______________________________              6    
```
So there are two extra rows, and we won't be actually reading the rows where we think our variables are.
The other format appears when error_status = 3:
```
 # PROCESS #
 # Power Reactor Optimisation Code #
 # PROCESS #
 # Power Reactor Optimisation Code #
 PROCESS_version_number__________________________________________________ (procver)_____________________     "1.0.13   "
 Date_of_run_____________________________________________________________ (date)________________________     "15/07/2019"
 Time_of_run_____________________________________________________________ (time)________________________     "23:13"
 User____________________________________________________________________ (username)____________________     "enmidol" 
 PROCESS_run_title_______________________________________________________ (runtitle)____________________     "Run Title (change this line using input variable 'runtitle')                                       
 PROCESS_tag_number______________________________________________________ (tagno)_______________________     "1.0.13-499-g78dfc55"                                                                               
 PROCESS_last_commit_message_____________________________________________ (commsg)______________________     "Reformat lines for inclusion in .bashrc as code.,"                                                 
 # Errors and Warnings #
 # Errors and Warnings #
 PROCESS_error_status_flag_______________________________________________ (error_status)________________              3    
 Final_error_identifier__________________________________________________ (error_id)____________________             74   
```
This is only a problem when instead of looking for determined numbers of rows and columns we look for keywords -this is one of the options available with the Extractor class-. COSSAN would enter in a loop trying to find keywords in the MFILE that don't actually exist.

If you use the Extractor with rows and columns you would be able to perform UQ analyses, but when ifail=6 and error_status=3 the variables you look for in the output will get wrong values (when the variables are shifted 2 rows forward) and NaNs. This is not really a problem if you are only looking for successful runs (ifail=1), as COSSAN will find the values for the defined variables (you can then filter the arrays saving the ones that correspond to ifail=1, as you know those would be the real values). However, you won't be able to explore regions of unfeasible runs (ifail=6).

So possible solutions:

The easiest way to fix this would be to remove the two extra rows included in the MFILE when ifail=6. These only state that PROCESS couldn't find a possible solution, so no major data would be lost with this.
This fix is suitable if we are interested in defining output variables in COSSAN using rows and columns, which can be a bit tedious. If we want to extract these variables by just telling COSSAN the name of the variable in the MFILE, we would have to solve the issue with the error_status=3, as COSSAN would enter in a loop trying to find keywords that are not inside.

I think the explanation may not be fully clear as you are not familiar with the COSSAN interface, and I feel this would be much easier to explain with a proper live example. Anyway, if you have any question please do let me know.

Thanks,

Enrique

[MFILE_ifail1.DAT](https://git.ccfe.ac.uk/process/process/uploads/99bbde833ef84b4ed9234371c3ce0d54/MFILE_ifail1.DAT)
[MFILE_ifail6.DAT](https://git.ccfe.ac.uk/process/process/uploads/5ba36f8cbdc787e5ced4d0f8b2234cf7/MFILE_ifail6.DAT)
[MFILE_errorstatus3.DAT](https://git.ccfe.ac.uk/process/process/uploads/dbced94b46181a9dbbdaf7af931896b6/MFILE_errorstatus3.DAT)

**Comment by clmould** [comment]
We provide MFILE readers in the `io` subpackage of PROCESS already, and this issue is outdated
