### ISSUE TITLE
Refprop error message in PROCESS error messages

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#898]
In GitLab by @skahn on Jul 25, 2019, 17:01

## Summary

The refprop error message are not integrated in the PROCESS error system.
It would be nice to have such an integration :)

Cheers

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

@mkovari @jmorris-uk @spicker

**Comment by clmould** [comment]
Refprop was removed for open sourcing so this issue is no longer applicable

**Comment by clmould** [comment]
Refprop was removed for open sourcing so this issue is no longer applicable
