### ISSUE TITLE
Centrepost Cooling Documentation Discrepancies

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#915]
In GitLab by @stuartmuldrew on Aug 6, 2019, 17:03

For the copper resistive centrepost model there are discrepancies between the equations written in the STAR user guide and what is coded in PROCESS.

For the temperature rise in the conductor:

![Screenshot_2019-08-06_at_16.42.29](https://git.ccfe.ac.uk/process/process/uploads/e627ed8f69a185c4051f334b4406edf9/Screenshot_2019-08-06_at_16.42.29.png)

![Screenshot_2019-08-06_at_16.42.41](https://git.ccfe.ac.uk/process/process/uploads/b04d7f009aed3874e4b4d0765d9122be/Screenshot_2019-08-06_at_16.42.41.png)

```fortran
!  Temperature rise in conductor,
!  for conduction from copper to coolant

dtcncpav = (ptot/volcp)/(2.0D0*kcp*(ro**2 - rcool**2) ) * &
     ( ro**2*rcool**2 - 0.25D0*rcool**4 - 0.75D0*ro**4 + ro**4 * &
     log(ro/rcool) )

dtconcpmx = (ptot/volcp)/(2.0D0*kcp) * &
     ( (rcool**2 - ro**2)/2.0D0 + ro**2 * log(ro/rcool) )
```

and the friction factor:

![Screenshot_2019-08-06_at_16.48.19](https://git.ccfe.ac.uk/process/process/uploads/e317d0781739e995a9b9bbfab4694b73/Screenshot_2019-08-06_at_16.48.19.png)

```fortran
    !  Thermal hydraulics: friction factor from Z. Olujic, Chemical
    !  Engineering, Dec. 1981, p. 91

    roughrat = 0.046D-3 / dcool
    fricfac = 1.0D0/ (-2.0D0 * log(roughrat/3.7D0 - 5.02D0/reyn * &
         log( roughrat/3.7D0 + 14.5D0/reyn) ) )**2
```

The main difference is the STAR guide uses ln elsewhere for natural log therefore one would assume this is base 10, however they are coded in PROCESS with base e. 

The subtraction in the denominator of ```dtcncpav```, ```ro**2 - rcool**2``` is the opposite way round to the STAR guide.

```dtconcpmx``` is wrong in the STAR guide by dimensional analysis.

Ref: @skahn

**Comment by chris-ashe** [comment]
This issue is now obsolete as the model now has the correct base 10 logarithm in all calculations
