### ISSUE TITLE
TF Straight height apparent inconsistency

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#935]
In GitLab by @skahn on Sep 23, 2019, 16:48

## Summary

`hr1` is used to define surfaces area for cryo system: 

```
    tfsai = 4.0D0 * tfno * tficrn * hr1
    tfsao = 2.0D0 * tfno * tficrn * (tfleng - 2.0D0*hr1)
```

but not set, except to 0 in the global variable file ...

Also to sure if why the upper curved part of the inner leg length is not containing the upper curved section 

Best regards

Seb

Ref : @mkovari, @jmorris-uk 

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by j-a-foster** [comment]
I removed `tfsai` and `tfsao` from `sctfcoil.py` as they were using the variable `hr1` which wasn't calculated or an input and just set to 0. A calculation that used `tfsai` was then replaced with `tfcryoarea` based on comments in the code (which have now been removed).
