### ISSUE TITLE
Bootstrap current fraction scaling formula for steady-state machines

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#954]
In GitLab by @mkovari on Nov 5, 2019, 11:43

[Derivation of bootstrap current fraction scaling formula for 0-D system code analysis](https://doi.org/10.1016/j.fusengdes.2019.111322) by Sakai:

They constructed new scaling formulas for the bootstrap current faction fBS for tokamaks with full non-inductive operation with positive shear safety factor q profiles (q increases monotonically with the radius). A fitting database was built by the ACCOME code, which contains 12,150 cases of self-consistent equilibria with q > 1.0 everywhere and q95 > 3.0.

The best formula contained the inverse aspect ratio, the poloidal beta, the internal inductance, q95/q(0), and the profile shape indices for density and temperature as input.  

All equilibria are fully non-inductive with neutral beam injection only.

This formula seems to be applicable to tokamak plasmas with a wide range of parameters. As far as I can see this is the recommended formula:  
![image](https://github.com/ukaea/PROCESS/assets/9718416/e4ef3e3d-694b-444e-b865-30320d7228bf)

Thanks to @asbrown for studying this paper.  Obviously I haven't read the paper.  Adam - do you want to comment or add more detail?  For example - can you fill in the range of applicability of this formula by giving upper and lower bounds for each of the six parameters?

Edit 19/3/24.
Process has a model for the diamagnetic current - this may need to be turned off when this this scaling is used:

> We created a fitting database for the $f_{BS}$ using the ACCOME code.  In this study, equilibria with the fully non-inductively driven conditions with neutral beam (NB) injection only are calculated, where the total plasma current is sustained by NB driven current together with the bootstrap current and the diamagnetic current. Note that the toroidal component of the diamagnetic current $I_{DI}$ was included in $f_{BS}$ in our fitting database; $f_{BS} = (I_{BS} + I_{DI})/I_P$.

Another question can arise - how does ACCOME divide up the current between bootstrap and beam-driven fractions?  

Note that Sakai does not include alphas or helium ions at all - the only impurity is carbon.

**Comment by mkovari** [comment]
This might be a good start for anyone who wants to actually implement a new model, but doesn't want to spend all year on it.
