### ISSUE TITLE
TF vertical bore not consistent for single null option

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#957]
In GitLab by @skahn on Nov 19, 2019, 10:43

## Description

In case of a single null, the upper and lower layers layout are not symmetric. For example the top section has also a breeding blancket while the lower section hasn't.

Current calculation of the vertical bore :
`tfborev = 2.0D0*(rminor*kappa + vgaptop + fwith + blnktth + vvblgap + shldtth + ddwi+ vgap2 + thshield + tftsgap)`

The lower divertor does not have a breeding blanket for instance, and I suspect the gaps differents.

Best regards
Sebastien    
Kahn

Ref : @stuartmuldrew, @mkovari, @jmorris-uk

**Comment by mkovari** [comment]
This variable is now called `build_variables.dh_tf_inner_bore`.  It is used only in `costs_2015.py`, which I suspect is never tested.

**Comment by mkovari** [comment]
Vertical Build
Top of TF coil 8.510
Bottom of TF coil  -9.744
Total = 18.254

Total height and width of TFC               18.254          13.673
